import {useState} from 'react';
import {useApi} from '../hooks/useApi';
import {Button,Input,DatePicker} from './ui';
export type AdditionalGuarantor=Record<string,string>;
export default function AdditionalGuarantors({tenantId,records,onSaved}:{tenantId:number;records:AdditionalGuarantor[];onSaved:()=>Promise<void>}){
 const api=useApi();const [draft,setDraft]=useState<AdditionalGuarantor[]|null>(null);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const change=(index:number,key:string,value:string)=>setDraft(items=>(items||[]).map((item,i)=>i===index?{...item,[key]:value}:item));
 const save=async()=>{setSaving(true);setError('');try{await api.put(`/api/tenants/${tenantId}/additional-guarantors`,{guarantors:draft||[]});setDraft(null);await onSaved();}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setSaving(false);}};
 return <div className="mt-6 border-t border-[var(--border-subtle)] pt-4"><div className="flex items-center justify-between"><h3 className="font-semibold text-sm">Additional Guarantors</h3>{draft===null&&<Button size="sm" variant="ghost" onClick={()=>setDraft(records.length?records:[{name:''}])}>{records.length?'Edit':'Add Guarantor'}</Button>}</div>
 {(draft||records).map((person,i)=><div key={i} className="rounded-lg bg-[var(--bg-subtle)] p-3 mt-3">{draft?<div className="grid sm:grid-cols-2 gap-3">{['name','address','email','phone','employment_status','employer','annual_income'].map(key=><Input key={key} label={key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} type={key==='annual_income'?'currency':key==='email'?'email':'text'} value={person[key]||''} onChange={value=>change(i,key,value)}/>)}<DatePicker label="Date of Birth" value={person.date_of_birth||''} onChange={value=>change(i,'date_of_birth',value)}/><Button size="sm" variant="outline" className="!text-red-600 !border-red-300" onClick={()=>setDraft(items=>(items||[]).filter((_,index)=>index!==i))}>Delete</Button><label className="sm:col-span-2 text-xs font-medium">Notes<textarea rows={4} value={person.notes||''} onChange={e=>change(i,'notes',e.target.value)} className="mt-2 w-full rounded-xl p-3 text-sm bg-[var(--bg-input)] border border-[var(--border-input)]" /></label></div>:<><p className="font-medium">{person.name}</p>{Object.entries(person).filter(([key,value])=>key!=='name'&&value).map(([key,value])=><p key={key} className="text-sm mt-1"><span className="text-[var(--text-muted)] capitalize">{key.replaceAll('_',' ')}: </span>{key==='annual_income'?`£${Number(value).toLocaleString('en-GB')}`:key==='date_of_birth'?new Date(value).toLocaleDateString('en-GB'):value}</p>)}</>}</div>)}
 {draft&&<div className="flex gap-2 mt-3"><Button size="sm" disabled={saving} onClick={save}>Save Guarantors</Button><Button size="sm" variant="ghost" onClick={()=>setDraft(null)}>Cancel</Button>{draft.length<4&&<Button size="sm" variant="ghost" onClick={()=>setDraft(items=>[...(items||[]),{name:''}])}>Add Another</Button>}</div>}{error&&<p role="alert" className="text-red-500 text-sm mt-2">{error}</p>}<p className="text-xs text-[var(--text-muted)] mt-3">Supporting files are held in Documents below, labelled with the guarantor’s name. Existing tenancy documents are retained without an application review step.</p></div>;
}
