import {useEffect,useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {CheckCircle} from 'lucide-react';
import {useApi} from '../hooks/useApi';
import {Button,Input,Select} from './ui';
type Details={landlordName:string;landlordAddress:string;companyNumber:string;landlordEmail:string;landlordPhone:string;serviceAddress:string;emergencyContact:string;directorName:string;depositScheme:string;bankAccountName?:string;bankSortCode?:string;bankAccountNumber?:string};
type State={landlordId:number;isCompany:boolean;defaults:Details;details:Details;directors:{id:number;name:string}[];saved:boolean;ready:boolean;serviceType:string;bank:{account_name:string;sort_code:string;account_number:string;approved_at:string}|null};
export default function ClientAgreementDetails({enquiryId,onReady}:{enquiryId:number;onReady:(ready:boolean)=>void}){
 const dirty=useRef(false),record=useRef(enquiryId);const [bankOverride,setBankOverride]=useState(false),[bankApproved,setBankApproved]=useState(false);
 const api=useApi();const [state,setState]=useState<State|null>(null),[details,setDetails]=useState<Details|null>(null),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;if(record.current!==enquiryId){dirty.current=false;record.current=enquiryId;}if(!dirty.current)onReady(false);api.get(`/api/tenant-enquiries/${enquiryId}/client-agreement-details`).then(v=>{if(active){setState(v);if(!dirty.current){setDetails(v.details);setBankOverride(v.bankOverride);setBankApproved(v.bankOverride&&!!v.bank?.approved_at);setSaved(v.saved);onReady(v.ready&&v.saved);}}}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[api,enquiryId,onReady]);
 const change=(key:keyof Details,value:string)=>{dirty.current=true;setDetails(d=>d?{...d,[key]:value}:d);setSaved(false);onReady(false);};
 const refresh=async()=>{setBusy(true);try{const v=await api.get(`/api/tenant-enquiries/${enquiryId}/client-agreement-details`);setState(v);dirty.current=true;setDetails(v.defaults);setBankOverride(false);setBankApproved(false);setSaved(false);onReady(false);setError('');}catch(e){setError(String(e));}finally{setBusy(false);}};
 const save=async()=>{if(!details)return;setBusy(true);setError('');try{const v=await api.put(`/api/tenant-enquiries/${enquiryId}/client-agreement-details`,{...details,bank_override_approved:bankApproved});dirty.current=false;setState(v);setSaved(true);onReady(v.ready);}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <section aria-label="Client agreement details" className={`rounded-xl border p-4 space-y-4 ${saved&&state?.ready?'border-emerald-500/40 bg-emerald-500/10':'border-[var(--border-input)]'}`}><h3 className="font-semibold flex items-center gap-2">Client Agreement Details{saved&&state?.ready&&<CheckCircle size={17} className="text-emerald-500"/>}</h3>{state&&details&&<fieldset disabled={busy} className="space-y-4"><p className="text-xs text-[var(--text-muted)]">All data has been sourced from the landlords record. <Link className="underline" to={`/landlords/${state.landlordId}`} target="_blank">Click here to open the record.</Link></p><div className="grid sm:grid-cols-2 gap-3">
 <Input label={state.isCompany?'Limited Company Name':'Landlord Name'} value={details.landlordName} onChange={v=>change('landlordName',v)}/><Input label={state.isCompany?'Companies Registered Address':'Landlords Correspondence Address'} value={details.landlordAddress} onChange={v=>change('landlordAddress',v)}/>
 {state.isCompany&&<><Input label="Company Number" value={details.companyNumber} onChange={v=>change('companyNumber',v)}/>{state.directors.length>0&&<Select label="Choose Director" value={state.directors.find(d=>d.name===details.directorName)?.name||''} onChange={v=>change('directorName',v)} options={[{value:'',label:'Choose or enter below'},...state.directors.map(d=>({value:d.name,label:d.name}))]}/>}<Input label="Director Signing on Behalf of Company" value={details.directorName} onChange={v=>change('directorName',v)}/></>}
 <Input label="Landlord Email" type="email" value={details.landlordEmail} onChange={v=>change('landlordEmail',v)}/><Input label="Landlord Phone" value={details.landlordPhone} onChange={v=>change('landlordPhone',v)}/><Input label="Address for Service in England or Wales" value={details.serviceAddress} onChange={v=>change('serviceAddress',v)}/><Input label="Emergency Contact" value={details.emergencyContact} onChange={v=>change('emergencyContact',v)}/></div>
 {state.isCompany&&<p className="text-sm">{details.directorName||'Director name'} · Signing on behalf of {details.landlordName||'limited company'}</p>}
 <div className={`p-3 rounded-xl text-sm ${state.bank?.approved_at?'bg-emerald-500/10':'bg-amber-500/10'}`}><p className="font-medium">Landlord Bank Details · {state.bank?.approved_at?'Approved':'Approval needed'}</p>{state.bank&&<p>{state.bank.account_name} · {state.bank.sort_code} · Account ending {state.bank.account_number.slice(-4)}</p>}<p className="text-xs mt-1">{state.serviceType==='let_only'?'Future rent uses the approved landlord account.':'Rent is collected into Fleming’s client-money account. These landlord details are for onward payments.'}</p>{!state.bank?.approved_at&&<p className="mt-2">Save and approve Bank Details on the landlord record, then refresh below.</p>}</div>
 <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={bankOverride} onChange={e=>{dirty.current=true;setBankOverride(e.target.checked);setBankApproved(false);setSaved(false);onReady(false);setDetails(d=>d?{...d,bankAccountName:'',bankSortCode:'',bankAccountNumber:''}:d);}}/>Use Alternative Bank Details for This Tenancy</label>{bankOverride&&<div className="space-y-3 border rounded-lg p-3"><p className="text-xs">These details apply to this agreement only. The landlord record keeps its approved bank details.</p><Input label="Account Name" value={details.bankAccountName||''} onChange={v=>{setBankApproved(false);change('bankAccountName',v);}}/><Input label="Sort Code" value={details.bankSortCode||''} onChange={v=>{setBankApproved(false);change('bankSortCode',v.replace(/\D/g,'').slice(0,6).match(/.{1,2}/g)?.join('-')||'');}}/><Input label="Account Number" value={details.bankAccountNumber||''} onChange={v=>{setBankApproved(false);change('bankAccountNumber',v.replace(/\D/g,'').slice(0,8));}}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={bankApproved} onChange={e=>{setBankApproved(e.target.checked);setSaved(false);onReady(false);}}/>I have checked and approve these details for this tenancy</label></div>}
 <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void refresh()}>Refresh From Landlord Record</Button><Button size="sm" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save Client Details'}</Button></div>{saved&&<p className="text-xs">{state.ready?'Client details saved and ready.':'Client details saved. Landlord bank approval is still needed.'}</p>}</fieldset>}{error&&<p role="alert" className="text-red-500 text-sm">{error}</p>}</section>;
}
