import {Building2} from 'lucide-react';
import {useNotifications} from '../context/NotificationContext';
import {createPortal} from 'react-dom';
import {useState} from 'react';
import {Button,GlassCard,Input} from './ui';
import {useApi,invalidateCache} from '../hooks/useApi';
type Member={id:number;name:string;role:string;department?:string;is_active:number};
type Team={id:number;name:string};
export default function DepartmentTeams({teams,users,onSaved}:{teams:Team[];users:Member[];onSaved:()=>Promise<void>}){
 const api=useApi();const {confirmAction}=useNotifications();const [open,setOpen]=useState(false),[editing,setEditing]=useState<number|null>(null),[name,setName]=useState(''),[members,setMembers]=useState<number[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const begin=(team?:Team)=>{setEditing(team?.id||null);setName(team?.name||'');setMembers(team?users.filter(u=>u.department===team.name).map(u=>u.id):[]);setError('');setOpen(true);};
 const save=async()=>{setBusy(true);setError('');try{const body={name,user_ids:members};if(editing)await api.put(`/api/departments/${editing}`,body);else await api.post('/api/departments',body);invalidateCache('/api/users');await onSaved();setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Could not save team');}finally{setBusy(false);}};
 const remove=async()=>{if(!editing||!await confirmAction(`Delete ${name}? Members will become unassigned and keep their accounts and access roles.`))return;setBusy(true);setError('');try{await api.delete(`/api/departments/${editing}`);invalidateCache('/api/users');await onSaved();setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Could not delete team');}finally{setBusy(false);}};
 const roles=[['admin','Administrators'],['manager','Managers'],['staff','Staff'],['viewer','Viewers']];
 return <GlassCard className="p-5 space-y-4"><div className="flex flex-wrap justify-between items-center gap-3"><h2 className="font-semibold flex items-center gap-2"><Building2 size={18}/>Team View</h2><Button size="sm" onClick={()=>begin()}>Create Department/Team</Button></div>
 <div className="grid md:grid-cols-2 gap-4">{[...teams,{id:0,name:'Unassigned'}].map(team=>{const list=users.filter(u=>u.is_active&&(team.id?u.department===team.name:!u.department));return <div key={team.id} className="rounded-xl border border-[var(--border-input)] p-4"><div className="flex justify-between gap-3"><h3 className="font-semibold">{team.name}</h3>{!!team.id&&<Button size="sm" variant="outline" onClick={()=>begin(team)}>Edit Team</Button>}</div>{roles.map(([role,label])=>{const group=list.filter(u=>u.role===role);return group.length?<div key={role} className="border-l-2 border-[var(--border-input)] ml-2 pl-4 mt-3"><p className="text-xs text-[var(--text-muted)]">{label}</p>{group.map(u=><p className="text-sm mt-1" key={u.id}>{u.name}</p>)}</div>:null;})}{!list.length&&<p className="text-sm mt-3 text-[var(--text-muted)]">No active members</p>}</div>;})}</div>
 {open&&createPortal(<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><div role="dialog" aria-modal="true" aria-label="Department / Team" className="bg-[var(--bg-card)] rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-auto space-y-4"><h2 className="font-semibold">{editing?'Edit Department/Team':'Create Department/Team'}</h2><Input label="Team Name" value={name} onChange={setName}/><fieldset><legend className="text-sm mb-2">Assign Existing Users</legend>{users.filter(u=>u.is_active||members.includes(u.id)).map(u=><label key={u.id} className="flex gap-2 items-center py-2 text-sm"><input type="checkbox" checked={members.includes(u.id)} onChange={e=>setMembers(e.target.checked?[...members,u.id]:members.filter(id=>id!==u.id))}/>{u.name}{u.department&&u.department!==name?` · currently ${u.department}`:''}</label>)}</fieldset><p className="text-xs text-[var(--text-muted)]">Each user belongs to one department. Assigning someone moves their team membership; their access role stays the same.</p>{error&&<p role="alert" className="text-red-500">{error}</p>}<div className="flex flex-wrap justify-end gap-2">{editing&&<Button variant="outline" className="mr-auto !text-red-600" disabled={busy} onClick={()=>void remove()}>Delete Team</Button>}<Button variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!name.trim()} onClick={()=>void save()}>Save Team</Button></div></div></div>,document.body)}
 </GlassCard>;
}
