import {useCallback,useEffect,useState} from 'react';
import {useApi} from '../hooks/useApi';
import {GlassCard,Button} from './ui';
type Status={connected:boolean;connected_at?:string;email?:string;plan?:string;error?:string;login?:{verificationUrl:string;userCode:string}};
export default function FlemoConnection(){
  const [provider,setProvider]=useState('ChatGPT');
  const api=useApi();const [status,setStatus]=useState<Status>({connected:false});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const refresh=useCallback(async()=>{try{setStatus(await api.get('/api/ai/account'));setError('');}catch(e){setError(e instanceof Error?e.message:'Could not read AI connection');}},[api]);
  useEffect(()=>{void refresh();},[refresh]);
  useEffect(()=>{if(!status.login)return;const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);},[status.login,refresh]);
  const connect=async()=>{setBusy(true);setError('');try{const login=await api.post('/api/ai/account/connect',{});setStatus({connected:false,login});}catch(e){setError(e instanceof Error?e.message:'Sign-in could not start');}finally{setBusy(false);}};
  const disconnect=async()=>{setBusy(true);setError('');try{await api.post('/api/ai/account/disconnect',{});setStatus({connected:false});}catch(e){setError(e instanceof Error?e.message:'Could not disconnect');}finally{setBusy(false);}};
  return <GlassCard className="p-6"><h2 className="text-lg font-semibold mb-2">Flemo AI Connection</h2><div role="group" aria-label="AI provider" className="grid grid-cols-5 gap-2 mb-4">{['ChatGPT','Claude','Gemini','Microsoft Copilot','Grok'].map(name=><Button key={name} className="!px-1 !py-2 !text-[10px] !rounded-xl flex-col gap-1 min-w-0" variant={provider===name?'gradient':'outline'} onClick={()=>setProvider(name)}><img src={`/ai-providers/${name.toLowerCase().replaceAll(' ','-')}.svg`} alt="" className="w-6 h-6 rounded bg-white p-0.5"/>{name==='Microsoft Copilot'?'Copilot':name}</Button>)}</div>{provider!=='ChatGPT'?<div className="rounded-xl bg-[var(--bg-subtle)] p-4 text-sm"><strong>{provider} — Setup Required</strong><p className="mt-2">This provider is not connected to Flemo. Provider API access and a CRM adapter must be configured before it can answer CRM questions.</p></div>:<><p className="text-sm text-[var(--text-muted)] mb-4">Connect your ChatGPT account to ask Flemo questions about CRM records and documents. Your account’s Codex usage limits apply. Relevant CRM information is shared with OpenAI when you ask a question.</p>
    {status.connected?<div className="grid grid-cols-1 gap-2"><p className="rounded-full min-h-14 flex flex-col justify-center text-center bg-emerald-500/15 border border-emerald-500/30 px-4 py-2 text-sm text-[var(--text-primary)]">Connected as {status.email || 'your ChatGPT account'}{status.plan?' · '+status.plan:''}<span className="block text-xs mt-1">{status.connected_at?'Connected '+new Date(status.connected_at).toLocaleString('en-GB'):'Connection date not recorded for this existing connection'}</span></p><Button variant="outline" className="!text-red-600 !border-red-300 hover:!bg-red-600 hover:!text-white w-full min-h-14" disabled={busy} onClick={disconnect}>Disconnect ChatGPT</Button></div>:status.login?<div className="space-y-3"><p className="text-sm">1. Open the sign-in page. 2. Enter this code and complete sign-in.</p><p className="font-mono text-2xl tracking-wider select-all">{status.login.userCode}</p><a className="inline-block rounded-lg bg-[#91236f] px-4 py-2 text-sm font-semibold text-white" href={status.login.verificationUrl} target="_blank" rel="noopener noreferrer">Sign in to ChatGPT</a><p className="text-xs text-[var(--text-muted)]">This page will update after you finish signing in. If asked, enable device-code login in your ChatGPT security settings.</p><button onClick={disconnect} disabled={busy} className="text-sm underline">Cancel sign-in</button></div>:<Button onClick={connect} disabled={busy}>{busy?'Opening sign-in…':'Connect ChatGPT'}</Button>}
    {(error||status.error)&&<p role="alert" className="text-sm text-red-500 mt-3">{error||status.error}</p>}
  </>}</GlassCard>;
}
