import {useEffect,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {useApi} from '../hooks/useApi';
import {Button,GlassCard,SectionHeader} from './ui';
export default function FreeAgentConnection(){
 const [provider,setProvider]=useState('FreeAgent');
 const {user}=useAuth();const api=useApi();const [state,setState]=useState<{configured:boolean;redirect_uri:string;connection?:{status:string;last_synced_at?:string;last_error?:string}}>();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{if(user?.role==='admin')void api.get('/api/freeagent/status').then(setState).catch(()=>setMessage('FreeAgent status could not be loaded'));},[api,user?.role]);
 if(user?.role!=='admin')return null;
 const act=async(action:string)=>{setBusy(true);setMessage('');try{const data=await api.post(`/api/freeagent/${action}`,{});if(data.url)window.location.assign(data.url);else {setMessage(`${data.imported} transactions imported for review.`);setState(await api.get('/api/freeagent/status'));}}catch(error){setMessage(error instanceof Error?error.message:'FreeAgent could not be updated');}finally{setBusy(false);}};
 return <GlassCard className="p-6"><SectionHeader title="Accountancy Software Integration"/><div className="flex gap-2 mb-4" role="group" aria-label="Accountancy provider">{['FreeAgent','Xero','Sage'].map(name=><Button key={name} variant={provider===name?'gradient':'outline'} onClick={()=>setProvider(name)}>{name}</Button>)}</div>{provider!=='FreeAgent'?<div className="rounded-xl bg-[var(--bg-subtle)] p-4 text-sm"><strong>{provider} — Setup Required</strong><p className="mt-2">This provider is not connected. An administrator needs to register the Fleming CRM application with {provider} and arrange its approved integration before bank transactions can be imported.</p><a className="underline block mt-3" href={provider==='Xero'?'https://developer.xero.com/documentation/guides/oauth2/auth-flow/':'https://developer.sage.com/'} target="_blank" rel="noopener noreferrer">Open {provider} Setup Guidance</a></div>:<><p className="text-sm mb-4">Connect the office FreeAgent account to import bank transactions into Bank Feed for review.</p><p className="text-sm mb-3">{state?.connection?.status==='connected'?'Connected':state?.configured?'Ready to connect':'App setup required'}</p>{state?.connection?.last_synced_at&&<p className="text-xs mb-3">Last import: {new Date(state.connection.last_synced_at).toLocaleString('en-GB')}</p>}<div className="flex gap-3 flex-wrap"><Button disabled={busy||!state?.configured} onClick={()=>void act('connect')}>{state?.connection?.status==='connected'?'Reconnect FreeAgent':'Connect FreeAgent'}</Button>{state?.connection?.status==='connected'&&<Button disabled={busy} onClick={()=>void act('sync')}>Import Transactions</Button>}</div><p role="status" className="text-sm mt-3">{message||state?.connection?.last_error}</p><details className="mt-3 text-sm"><summary className="cursor-pointer">Account Setup Instructions</summary><ol className="list-decimal ml-5 mt-3 space-y-2"><li>In the FreeAgent Developer Dashboard, open the Fleming CRM app.</li><li>Add this callback to its redirect URLs: <span className="break-all select-all">{state?.redirect_uri}</span></li><li>Save, then select Connect FreeAgent here. Sign in to the office account and approve access.</li><li>Select Import Transactions. Review entries in Bank Feed before recording rent or expenses.</li></ol></details></>}</GlassCard>;
}
