import {useEffect,useState} from 'react';
import {Landmark,CheckCircle} from 'lucide-react';
import {useApi} from '../hooks/useApi';
import {Button,GlassCard,Input} from './ui';
export default function LandlordBankDetails({landlordId}:{landlordId:number}){
 const api=useApi();const [data,setData]=useState({account_name:'',sort_code:'',account_number:'',bank_name:''}),[approved,setApproved]=useState(false),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;api.get(`/api/landlords/${landlordId}/bank-details`).then(v=>{if(active){setData({account_name:v.account_name||'',sort_code:v.sort_code||'',account_number:v.account_number||'',bank_name:v.bank_name||''});setApproved(!!v.approved_at);setSaved(!!v.approved_at);}}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[api,landlordId]);
 const change=(key:string,value:string)=>{setData(d=>({...d,[key]:value}));setApproved(false);setSaved(false);};
 const save=async()=>{setBusy(true);setError('');try{const result=await api.put(`/api/landlords/${landlordId}/bank-details`,{...data,details_approved:approved});setSaved(!!result.approved_at);}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <GlassCard className={`p-6 ${saved?'!border-emerald-500/40 !bg-emerald-500/10':''}`}><h2 className="font-semibold flex items-center gap-2"><Landmark size={18}/>Bank Details{saved&&<span className="ml-auto text-sm text-emerald-600 flex gap-2 items-center"><CheckCircle size={16}/>Approved</span>}</h2><fieldset disabled={busy}><div className="grid sm:grid-cols-2 gap-4 mt-4"><Input label="Account Name" value={data.account_name} onChange={v=>change('account_name',v)}/><Input label="Sort Code" value={data.sort_code} onChange={v=>change('sort_code',v)}/><Input label="Account Number" value={data.account_number} onChange={v=>change('account_number',v)}/><Input label="Bank Name (optional)" value={data.bank_name} onChange={v=>change('bank_name',v)}/></div><label className="flex gap-2 items-center mt-4 text-sm"><input type="checkbox" checked={approved} onChange={e=>{setApproved(e.target.checked);setSaved(false);}}/>Details approved</label><p className="text-xs text-[var(--text-muted)] mt-2">Confirm these details have been checked. Editing them requires approval again.</p></fieldset>{error&&<p role="alert" className="text-red-500 mt-3">{error}</p>}<Button className="mt-4" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save Bank Details'}</Button></GlassCard>;
}
