import {useEffect,useRef,useState} from 'react';
import {Landmark,Check,ShieldCheck,Pencil} from 'lucide-react';
import {useApi} from '../hooks/useApi';
import {useAuth} from '../context/AuthContext';
import {useNotifications} from '../context/NotificationContext';
import {Button,GlassCard,Input} from './ui';
type Bank={account_name:string;sort_code:string;account_number:string;bank_name:string;approved_at?:string;approved_by_name?:string};
const empty:Bank={account_name:'',sort_code:'',account_number:'',bank_name:''};
export default function LandlordBankDetails({landlordId}:{landlordId:number}){
 const api=useApi();const {user}=useAuth();const {confirmAction}=useNotifications();const [record,setRecord]=useState<Bank>(empty),[draft,setDraft]=useState<Bank>(empty),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const editingRef=useRef(false);
 useEffect(()=>{let active=true;api.get(`/api/landlords/${landlordId}/bank-details`).then(v=>{if(active){const next={...empty,...v};setRecord(next);if(!editingRef.current)setDraft(next);}}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[api,landlordId]);
 const edit=()=>{setDraft(record);editingRef.current=true;setEditing(true);setError('');};
 const cancel=()=>{editingRef.current=false;setEditing(false);setDraft(record);setError('');};
 const save=async(approve=false)=>{if(approve&&!await confirmAction('Approve these bank details for rent payments?','Approve Bank Details'))return;setBusy(true);setError('');try{const result=await api.put(`/api/landlords/${landlordId}/bank-details`,{...(approve?record:draft),details_approved:approve});setRecord({...empty,...result});setDraft({...empty,...result});editingRef.current=false;setEditing(false);}catch(e){setError(e instanceof Error?e.message:'Could not save bank details');}finally{setBusy(false);}};
 return <GlassCard className={`p-6 ${record.approved_at&&!editing?'!border-emerald-500/40 !bg-emerald-500/10':''}`}><div className="flex flex-wrap justify-between items-center gap-3"><h2 className="font-semibold flex items-center gap-2"><Landmark size={18}/>Bank Details</h2>{!editing&&<Button size="sm" variant="outline" onClick={edit}><Pencil size={14} className="mr-2"/>Update Details</Button>}</div>
 {editing?<fieldset disabled={busy} className="mt-4"><div className="grid sm:grid-cols-2 gap-4"><Input label="Account Name" value={draft.account_name} onChange={v=>setDraft(d=>({...d,account_name:v}))}/><Input label="Sort Code" value={draft.sort_code} onChange={v=>setDraft(d=>({...d,sort_code:v.replace(/\D/g,'').slice(0,6).match(/.{1,2}/g)?.join('-')||''}))}/><Input label="Account Number" value={draft.account_number} onChange={v=>setDraft(d=>({...d,account_number:v.replace(/\D/g,'').slice(0,8)}))}/><Input label="Bank Name" value={draft.bank_name} onChange={v=>setDraft(d=>({...d,bank_name:v}))}/></div><p className="text-xs text-[var(--text-muted)] mt-3">Saving updated details requires administrator approval again.</p><div className="flex justify-end gap-2 mt-4"><Button variant="ghost" onClick={cancel}>Cancel</Button><Button onClick={()=>void save()}>{busy?'Saving…':'Save Bank Details'}</Button></div></fieldset>:<><div className="grid sm:grid-cols-2 gap-4 mt-4">{[['Account Name',record.account_name],['Sort Code',record.sort_code],['Account Number',record.account_number],['Bank Name',record.bank_name]].map(([label,value])=><div key={label}><p className="text-xs text-[var(--text-muted)]">{label}</p><p className="text-sm font-medium mt-1">{value||'—'}</p></div>)}</div><div className="rounded-xl border border-[var(--border-input)] p-4 mt-4">{record.approved_at?<div className="flex items-center gap-3"><span className="w-9 h-9 shrink-0 rounded-full bg-emerald-500/15 text-emerald-600 grid place-items-center"><Check size={20}/></span><div><p className="text-sm font-semibold">Details Approved</p><p className="text-xs text-[var(--text-muted)]">{new Date(record.approved_at).toLocaleDateString('en-GB')}{record.approved_by_name?` · ${record.approved_by_name}`:''}</p></div></div>:<><p className="text-xs text-[var(--text-muted)] mb-3">Check the saved bank details before approving them for rent payments.</p>{user?.role==='admin'?<Button variant="outline" className="w-full" disabled={busy||!record.account_name} onClick={()=>void save(true)}><ShieldCheck size={15} className="mr-2"/>Approve Details (Admin)</Button>:<p className="text-sm">Awaiting administrator approval</p>}</>}</div></>}{error&&<p role="alert" className="text-red-500 mt-3">{error}</p>}</GlassCard>;
}
