import {useEffect,useState} from 'react';
import {ShieldCheck,Plus} from 'lucide-react';
import {useApi} from '../hooks/useApi';
import {Button,GlassCard,SectionHeader,Input,Select,DatePicker} from './ui';
type Policy={id:number;cost_included_in_service_charge?:boolean;policy_type:string;policy_number:string;annual_cost:string;allocated_cost:string;commencement_date:string;expiry_date:string;insurer?:string;broker_company?:string;broker_name:string;broker_email:string;broker_phone:string;properties:{id:number;address:string;allocated_cost:string}[]};
export default function PropertyInsurance({propertyId}:{propertyId:number}){
 const api=useApi();const [rows,setRows]=useState<Policy[]>([]);const [properties,setProperties]=useState<{id:number;address:string;landlord_type:string}[]>([]);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [form,setForm]=useState({cost_included_in_service_charge:false,policy_type:'buildings',policy_number:'',annual_cost:'',commencement_date:'',expiry_date:'',insurer:'',broker_company:'',broker_name:'',broker_phone:'',broker_email:'',property_ids:[propertyId]});
 useEffect(()=>{let active=true;Promise.all([api.get(`/api/properties/${propertyId}/policies`),api.get('/api/properties')]).then(([r,p])=>{if(active){setRows(r);setProperties(p.filter((v:{landlord_type:string})=>v.landlord_type==='internal'));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[api,propertyId]);
 const save=async()=>{setBusy(true);setError('');try{await api.post(`/api/properties/${propertyId}/policies`,{...form,annual_cost:Number(form.annual_cost)});setRows(await api.get(`/api/properties/${propertyId}/policies`));setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}};
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'});
 return <GlassCard className="p-4 sm:p-6"><SectionHeader title="Insurance" icon={<ShieldCheck size={16}/>}/><p className="text-sm mb-4">Annual rent protection and buildings cover. A shared premium is split equally across the selected properties and recorded once in their costs.</p><div className="grid sm:grid-cols-2 gap-3 mb-4">{['buildings','rent_protection'].map(type=>{const current=rows.filter(p=>p.policy_type===type&&p.commencement_date.slice(0,10)<=today&&p.expiry_date.slice(0,10)>=today);return <div key={type} className={`rounded-xl p-3 text-sm ${current.length?'bg-emerald-500/15 border border-emerald-500/30 text-[var(--text-primary)]':'bg-[var(--bg-subtle)]'}`}><strong>{type==='buildings'?'Buildings Insurance':'Rent Protection'}</strong><p>Policy in Place: {current.length?'Yes':'Not Recorded'}</p></div>;})}</div>
 <Button size="sm" onClick={()=>setOpen(!open)}><Plus size={14}/> {open?'Close Policy Form':'Add Policy / Renewal'}</Button>
 {open&&<div className="mt-4 rounded-xl border border-[var(--border-input)] p-4 space-y-4"><div className="grid sm:grid-cols-2 gap-4"><Select label="Policy Type" value={form.policy_type} onChange={policy_type=>setForm(f=>({...f,policy_type}))} options={[{value:'buildings',label:'Buildings Insurance'},{value:'rent_protection',label:'Rent Protection'}]}/>{form.cost_included_in_service_charge?<p className="text-sm self-center text-[var(--feedback-emerald)]">Included in service charge · no additional cost</p>:<Input label="Annual Cover Cost (£)" value={form.annual_cost} onChange={annual_cost=>setForm(f=>({...f,annual_cost}))}/>}<Input label="Policy Number" value={form.policy_number} onChange={policy_number=>setForm(f=>({...f,policy_number}))}/><DatePicker label="Commencement Date" value={form.commencement_date} onChange={commencement_date=>setForm(f=>({...f,commencement_date}))}/><DatePicker label="Expiry Date" value={form.expiry_date} onChange={expiry_date=>setForm(f=>({...f,expiry_date}))}/><Input label="Insurer" value={form.insurer} onChange={insurer=>setForm(f=>({...f,insurer}))}/><Input label="Broker Company" value={form.broker_company} onChange={broker_company=>setForm(f=>({...f,broker_company}))}/><Input label="Broker Name" value={form.broker_name} onChange={broker_name=>setForm(f=>({...f,broker_name}))}/><Input label="Broker Phone" value={form.broker_phone} onChange={broker_phone=>setForm(f=>({...f,broker_phone}))}/><Input label="Broker Email" value={form.broker_email} onChange={broker_email=>setForm(f=>({...f,broker_email}))}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.cost_included_in_service_charge} onChange={e=>setForm(f=>({...f,cost_included_in_service_charge:e.target.checked,annual_cost:e.target.checked?'0':''}))}/>Insurance cost is included in the service charge</label><fieldset><legend className="text-sm font-semibold mb-2">Properties Covered</legend><div className="grid sm:grid-cols-2 gap-2">{properties.map(p=><label key={p.id} className="text-sm flex gap-2"><input type="checkbox" checked={form.property_ids.includes(p.id)} disabled={p.id===propertyId} onChange={e=>setForm(f=>({...f,property_ids:e.target.checked?[...f.property_ids,p.id]:f.property_ids.filter(id=>id!==p.id)}))}/>{p.address}</label>)}</div></fieldset><p className="text-xs text-[var(--text-muted)]">Save the actual annual premium once. Add a new policy for each renewal so historic costs and coverage dates remain available.</p><Button variant="ghost" disabled={busy} onClick={()=>{setOpen(false);setError('');}}>Cancel</Button><Button disabled={busy||!form.annual_cost||!form.commencement_date||!form.expiry_date} onClick={()=>void save()}>{busy?'Saving…':'Save Policy & Annual Cost'}</Button></div>}
 {error&&<p role="alert" className="text-sm text-red-500 mt-3">{error}</p>}<div className="space-y-3 mt-4">{rows.map(p=>{const days=Math.ceil((Date.parse(p.expiry_date.slice(0,10))-Date.parse(today))/86400000);return <div key={p.id} className={`rounded-xl border p-4 ${days<=14?'border-red-400':'border-[var(--border-subtle)]'}`}><p className="font-semibold">{p.policy_type==='buildings'?'Buildings Insurance':'Rent Protection'} · {p.policy_number||'No Policy Number'}</p><p className="text-sm">{p.commencement_date.slice(0,10)} — {p.expiry_date.slice(0,10)}{days<=14?<strong className="text-red-500"> · {days<0?'Expired':`Renew within ${days} days`}</strong>:null}</p>{p.cost_included_in_service_charge?<p className="text-sm text-[var(--feedback-emerald)]">Included in service charge · no separate insurance cost</p>:<p className="text-sm">Annual Premium: £{Number(p.annual_cost).toLocaleString('en-GB',{minimumFractionDigits:2})} · This Property: £{Number(p.allocated_cost).toLocaleString('en-GB',{minimumFractionDigits:2})}</p>}<p className="text-sm">Insurer: {p.insurer||'Not Recorded'}</p><p className="text-sm">Broker: {[p.broker_company,p.broker_name,p.broker_phone,p.broker_email].filter(Boolean).join(' · ')||'Not Recorded'}</p><p className="text-xs text-[var(--text-muted)]">Covered: {p.properties.map(p=>p.address).join(', ')}</p></div>;})}</div></GlassCard>;
}
