import {useNotifications} from '../context/NotificationContext';
import {useEffect,useState} from 'react';
import {ClipboardCheck,Upload,Send,Download} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {useApi} from '../hooks/useApi';
import {GlassCard,SectionHeader,Select,DatePicker,Button} from './ui';
const API=import.meta.env.VITE_API_URL || '';
type RecordRow={id:number;tenant_id:number;signed_date?:string;inspection_date:string;filename?:string;review_issued_at?:string;reviews?:{id:number;review_url:string;name:string;signed_at?:string;due_date:string;email_id?:string;email_error?:string;sms_id?:string;sms_error?:string}[]};
type ReviewDetails={id:number;tenant_name:string;signature_name?:string;signed_at?:string;general_comments?:string;photos:{id:number;room_name?:string;caption?:string;approved:boolean;comment?:string}[];added_photos:{id:number;caption:string}[]};
export default function PropertyInventory({propertyId,tenants,onSaved}:{onSaved?:()=>void;propertyId:number;tenants:{id:number;name:string;tenancy_start_date?:string|null}[]}) {
 const api=useApi();const {confirmAction}=useNotifications();const {token,user}=useAuth();const [rows,setRows]=useState<RecordRow[]>([]);const [tenantId,setTenantId]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [signedDate,setSignedDate]=useState('');const [editing,setEditing]=useState(false);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const completed=rows.find(row=>String(row.tenant_id)===tenantId && row.signed_date);
 const locked=!!completed&&!editing;
 const [reviewDetails,setReviewDetails]=useState<Record<number,ReviewDetails>>({});
 const load=()=>api.get(`/api/properties/${propertyId}/inventory-records`).then(setRows);
 useEffect(()=>{let active=true;api.get(`/api/properties/${propertyId}/inventory-records`).then(data=>{if(active)setRows(data);}).catch(()=>{if(active)setMessage('Could not load inventories');});return()=>{active=false;};},[propertyId,api]);
 const upload=async()=>{if(!file)return;setBusy(true);setMessage('');try{const body=new FormData();body.append('file',file);body.append('tenant_id',tenantId);body.append('inspection_date',date);body.append('signed_date',signedDate);if(editing&&completed)body.append('inventory_id',String(completed.id));const res=await fetch(`${API}/api/properties/${propertyId}/inventory-document`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const data=await res.json();if(!res.ok)throw new Error(data.error);setFile(null);setEditing(false);await load();onSaved?.();setMessage('Signed inventory saved in this property and tenant Documents.');}catch(error){setMessage(error instanceof Error?error.message:'Upload failed');}finally{setBusy(false);}};
 const send=async(id:number)=>{if(!await confirmAction('Send this inventory to its tenants by email and SMS? The issued inventory will be locked.'))return;setBusy(true);try{const data=await api.post(`/api/inventories/${id}/review`,{});await load();setMessage(data.delivery.map((r:{tenant:string;email:string;sms:string})=>`${r.tenant}: email ${r.email}; SMS ${r.sms}`).join(' · '));}catch(error){setMessage(error instanceof Error?error.message:'Could not send');}finally{setBusy(false);}};
 const download=async(id:number)=>{try{const res=await fetch(`${API}/api/inventories/${id}/document`,{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)throw new Error('Download failed');const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='inventory.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){setMessage(String(error));}};
 const openReview=async(inventoryId:number,reviewId:number)=>{try{const details=await api.get(`/api/inventories/${inventoryId}/reviews/${reviewId}`);setReviewDetails(current=>({...current,[reviewId]:details}));}catch{setMessage('Could not load tenant comments');}};
 const downloadEvidence=async(inventoryId:number,reviewId:number,photoId:number)=>{try{const response=await fetch(`${API}/api/inventories/${inventoryId}/reviews/${reviewId}/photos/${photoId}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Photo unavailable');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`inventory-evidence-${photoId}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setMessage('Could not download photo');}};
 return <GlassCard className="p-4 sm:p-6"><SectionHeader title="Inventory" icon={<ClipboardCheck size={16}/>}/><p className="text-sm text-[var(--text-secondary)] mb-4">Please upload the completed and signed inventory conducted at the handover of the property.</p>
 <Select label="Select Tenancy" value={tenantId} onChange={value=>{setTenantId(value);setEditing(false);setFile(null);}} options={[{value:'',label:'Choose Tenant / Tenancy'},...tenants.map(t=>({value:String(t.id),label:`${t.name}${t.tenancy_start_date?' · '+t.tenancy_start_date.slice(0,10):''}`}))]}/>
 <fieldset disabled={locked||busy} className={locked?'opacity-60 mt-3':'mt-3'}><div className="grid sm:grid-cols-2 gap-3"><DatePicker label="Inventory Completed Date" value={locked?completed!.inspection_date.slice(0,10):date} onChange={setDate}/><DatePicker label="Inventory Signed Date" value={locked?completed!.signed_date!.slice(0,10):signedDate} onChange={setSignedDate}/></div>
 {!locked&&<label className="mt-3 flex items-center gap-3 border border-[var(--border-input)] bg-[var(--bg-input)] rounded-xl p-3 cursor-pointer"><Upload size={18}/><span className="text-sm truncate">{file?.name || 'Choose Signed Inventory PDF (up to 25 MB)'}</span><input aria-label="Signed Inventory PDF" type="file" accept="application/pdf,.pdf" className="sr-only" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}
 {!locked&&<Button className="mt-3" size="sm" disabled={busy||!file||!tenantId||!date||!signedDate} onClick={upload}>{editing?'Save Changes':'Save Signed Inventory'}</Button>}</fieldset>
 {completed&&<div className="flex flex-wrap gap-2 mt-3"><Button size="sm" variant="outline" onClick={()=>download(completed.id)}><Download size={14}/> View Completed Inventory</Button>{user?.role==='admin'&&!completed.review_issued_at&&<><Button size="sm" variant="outline" onClick={()=>{setDate(completed.inspection_date.slice(0,10));setSignedDate(completed.signed_date!.slice(0,10));setEditing(true);}}>Edit Inventory</Button><Button size="sm" variant="outline" className="!text-red-600" onClick={async()=>{if(!await confirmAction('Delete this completed inventory and its Documents links?'))return;try{await api.delete(`/api/inventories/${completed.id}`);await load();onSaved?.();setEditing(false);}catch(e){setMessage(e instanceof Error?e.message:'Delete failed');}}}>Delete Inventory</Button></>}</div>}
 <p role="status" className="text-sm mt-3">{message}</p><div className="space-y-3 mt-4">{rows.map(row=><div key={row.id} className="p-4 rounded-xl bg-[var(--bg-subtle)]"><p className="font-medium">{row.filename || `App inspection #${row.id}`}</p><p className="text-xs text-[var(--text-muted)]">{row.inspection_date.slice(0,10)}</p><div className="flex flex-wrap gap-2 mt-2">{row.filename&&<Button size="sm" onClick={()=>download(row.id)}><Download size={14}/> Download</Button>}{!row.review_issued_at&&!row.signed_date&&<Button size="sm" disabled={busy} onClick={()=>send(row.id)}><Send size={14}/> Send for review</Button>}</div>{row.reviews?.map(review=><div key={review.id}><p className="text-sm mt-2">{review.name}: {review.signed_at?'Signed '+new Date(review.signed_at).toLocaleDateString('en-GB'):'Awaiting signature'} · Review by {review.due_date.slice(0,10)}{review.email_error?` · Email: ${review.email_error}`:''}{review.sms_error?` · SMS: ${review.sms_error}`:''}</p>
 <button className="text-sm underline mt-2 mr-4" onClick={async()=>{try{await navigator.clipboard.writeText(review.review_url);setMessage(`Review link copied for ${review.name}`);}catch{setMessage(`Review link: ${review.review_url}`);}}}>Copy review link</button>
 <button className="text-sm underline mt-2" onClick={()=>openReview(row.id,review.id)}>Read tenant review</button>
 {reviewDetails[review.id]&&<div className="mt-3 p-3 border border-[var(--border-input)] rounded-lg space-y-2">
 <p className="text-sm whitespace-pre-wrap">{reviewDetails[review.id].general_comments || 'No general comments'}</p>
 {reviewDetails[review.id].photos.map(photo=><p key={photo.id} className="text-sm whitespace-pre-wrap"><strong>{photo.room_name || 'Photo'}{photo.caption?' · '+photo.caption:''}:</strong> {photo.comment || (photo.approved?'Approved':'Not yet reviewed')}</p>)}
 {reviewDetails[review.id].added_photos.map(photo=><div key={photo.id}><p className="text-sm whitespace-pre-wrap">{photo.caption}</p><button className="text-sm underline" onClick={()=>downloadEvidence(row.id,review.id,photo.id)}>Download tenant photo</button></div>)}
 {reviewDetails[review.id].signature_name&&<p className="text-sm font-medium">Signed by {reviewDetails[review.id].signature_name}</p>}
 </div>}</div>)}</div>)}</div></GlassCard>;
}
