import {useEffect,useState} from 'react';
import {Search,Upload,Download} from 'lucide-react';
import {Button,GlassCard,Select,DatePicker} from './ui';
import {useApi} from '../hooks/useApi';
import {useAuth} from '../context/AuthContext';
import {useNotifications} from '../context/NotificationContext';
type Inspection={id:number;inspection_date:string;condition:string;conducted_by:number;conducted_by_name:string;completed_at:string;document_id:number|null;document_name:string;notes:string};
type State={assigned_to?:string;enabled:boolean;next_due:string|null;tenant?:{name:string};inspections:Inspection[]};
const API=import.meta.env.VITE_API_URL||'';
export default function PropertyInspections({propertyId}:{propertyId:number}){
 const api=useApi();const {token,user}=useAuth();const {confirmAction}=useNotifications();const [state,setState]=useState<State|null>(null),[members,setMembers]=useState<{id:number;name:string;role:string}[]>([]),[documents,setDocuments]=useState<{id:number;original_name:string}[]>([]);
 const [assigning,setAssigning]=useState(false),[assignee,setAssignee]=useState('');
 const [editing,setEditing]=useState<number|null>(null);
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[staff,setStaff]=useState(String(user?.id||'')),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[condition,setCondition]=useState('good'),[documentId,setDocumentId]=useState(''),[notes,setNotes]=useState('');
 useEffect(()=>{let active=true;api.get(`/api/properties/${propertyId}/inspections`).then(data=>{if(active)setState(data);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[api,propertyId]);
 const begin=async(row?:Inspection)=>{setEditing(row?.id||null);setDate(row?row.inspection_date.slice(0,10):new Date().toISOString().slice(0,10));setCondition(row?.condition||'good');setStaff(String(row?.conducted_by||user?.id||''));setDocumentId(row?.document_id?String(row.document_id):'');setNotes(row?.notes||'');try{const [users,docs]=await Promise.all([api.get('/api/users/options'),api.get(`/api/documents/property/${propertyId}`)]);setMembers(users.filter((u:{role:string})=>u.role!=='viewer'));setDocuments(docs);setOpen(true);setError('');}catch(e){setError(String(e));}};
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);form.append('doc_type','Property Inspection Report');const response=await fetch(`${API}/api/documents/property/${propertyId}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});const doc=await response.json();if(!response.ok)throw new Error(doc.error);setDocuments(await api.get(`/api/documents/property/${propertyId}`));setDocumentId(String(doc.id));}catch(e){setError(String(e));}finally{setBusy(false);}};
 const save=async()=>{if(!await confirmAction(editing?'Save these inspection changes?':'Confirm this property inspection is complete?'))return;setBusy(true);setError('');try{const body={inspection_date:date,condition,conducted_by:Number(staff),document_id:Number(documentId),notes};if(editing)await api.put(`/api/properties/${propertyId}/inspections/${editing}`,body);else await api.post(`/api/properties/${propertyId}/inspections`,body);setState(await api.get(`/api/properties/${propertyId}/inspections`));setOpen(false);setNotes('');setDocumentId('');}catch(e){setError(String(e));}finally{setBusy(false);}};
 const download=async(row:Inspection)=>{try{const response=await fetch(`${API}/api/documents/download/${row.document_id}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Report could not be downloaded');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=row.document_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}};
 if(state&&!state.enabled)return null;
 return <GlassCard className="p-4 sm:p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold flex items-center gap-2"><Search size={18}/> Property Inspections</h2></div>
 <div className="mt-4 rounded-xl border border-[var(--border-input)] p-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm">Next Inspection Due: <strong>{state?.next_due?new Date(state.next_due).toLocaleDateString('en-GB'):'Add a tenancy to start the schedule'}</strong></p><p className="text-xs text-[var(--text-muted)] mt-1">At 3 and 6 months after tenancy start, then every 12 months.</p></div>{state?.next_due&&user?.role!=='viewer'&&<div className="flex gap-2"><Button size="sm" variant="outline" onClick={async()=>{try{setMembers((await api.get('/api/users/options')).filter((u:{role:string})=>u.role!=='viewer'));setAssignee(state.assigned_to||'');setAssigning(true);}catch(e){setError(String(e));}}}>Assign To</Button>{!open&&<Button size="sm" onClick={()=>void begin()}>Record Inspection</Button>}</div>}</div>
 {assigning&&<div className="mt-3 flex flex-wrap items-end gap-3"><Select label="Assign Inspection To" value={assignee} onChange={setAssignee} options={[{value:'',label:'Unassigned'},...members.map(m=>({value:String(m.id),label:m.name}))]}/><Button disabled={busy} onClick={async()=>{setBusy(true);try{await api.put(`/api/properties/${propertyId}/inspections/assignment`,{assigned_to:assignee});setState(await api.get(`/api/properties/${propertyId}/inspections`));setAssigning(false);setError('');}catch(e){setError(String(e));}finally{setBusy(false);}}}>Save Assignment</Button><Button variant="ghost" onClick={()=>setAssigning(false)}>Cancel</Button></div>}
 {open&&<div className="space-y-4 mt-5 rounded-xl border border-[var(--border-input)] p-4"><div className="grid sm:grid-cols-2 gap-4"><Select label="Inspection Conducted By" value={staff} onChange={setStaff} options={[{value:'',label:'Choose staff member'},...members.map(m=>({value:String(m.id),label:m.name}))]}/><DatePicker label="Inspection Date" value={date} onChange={setDate}/><Select label="Condition Report" value={condition} onChange={setCondition} options={[{value:'bad',label:'Bad'},{value:'needs_repair',label:'Needs Repair'},{value:'good',label:'Good'},{value:'excellent',label:'Excellent'}]}/><Select label="Inspection Report" searchable value={documentId} onChange={setDocumentId} options={[{value:'',label:'Choose existing report or upload'},...documents.map(d=>({value:String(d.id),label:d.original_name}))]}/></div>
 <label className="flex items-center justify-center gap-2 rounded-xl border-2 border-dashed border-[var(--border-input)] p-4 cursor-pointer text-sm"><Upload size={18}/>{busy?'Uploading…':'Upload Inspection Report'}<input aria-label="Upload Inspection Report" className="sr-only" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/></label>
 <label className="block text-sm">Notes<textarea className="block w-full mt-2 rounded-xl p-3 bg-[var(--bg-input)] border border-[var(--border-input)]" value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="flex justify-end gap-2"><Button variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!staff||!date||!documentId} onClick={()=>void save()}>{editing?'Save Changes':'Confirm Complete'}</Button></div></div>}
 {error&&<p role="alert" className="text-sm text-red-500 mt-3">{error}</p>}
 <div className="space-y-3 mt-4">{state?.inspections.map(row=><div key={row.id} className="p-4 rounded-xl bg-[var(--bg-subtle)]"><div className="flex justify-between gap-3"><p className="font-medium">{new Date(row.inspection_date).toLocaleDateString('en-GB')} · <span className={['good','excellent'].includes(row.condition)?'text-[var(--feedback-emerald)]':'text-red-600'}>{row.condition.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}</span></p>{row.document_id&&<Button size="sm" variant="outline" onClick={()=>void download(row)}><Download size={14}/> Report</Button>}</div>{user?.role==='admin'&&<div className="flex gap-2 my-3"><Button size="sm" variant="outline" onClick={()=>void begin(row)}>Edit Inspection</Button><Button size="sm" variant="outline" className="!text-red-600" onClick={async()=>{if(!await confirmAction('Delete this inspection and its report? Reports shared with another inspection or expense will be kept.'))return;try{await api.delete(`/api/properties/${propertyId}/inspections/${row.id}`);setState(await api.get(`/api/properties/${propertyId}/inspections`));}catch(e){setError(String(e));}}}>Delete Inspection</Button></div>}<p className="text-sm">Conducted by {row.conducted_by_name}</p><p className="text-xs text-[var(--text-muted)]">Confirmed complete {new Date(row.completed_at).toLocaleDateString('en-GB')}</p>{row.notes&&<p className="text-sm mt-2 whitespace-pre-wrap">{row.notes}</p>}</div>)}</div></GlassCard>;
}
