import {useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useApi} from '../hooks/useApi';
import {useAuth} from '../context/AuthContext';
import {useNotifications} from '../context/NotificationContext';
import {Button,Card,Input} from './ui';
type Agreement={id:number;property_id:number;property_address?:string;service_type:string;setup_fee:number;monthly_fee:number;status:string;issued_at?:string;signed_at?:string;signer_name?:string;signing_url:string;delivery_status?:string;delivery_error?:string;bank_changed:boolean;bank_details:{account_name:string;sort_code:string;account_number:string;bank_name:string}};
type Context={property:{landlord_type:string;service_type:string};directors:{name:string}[];agreements:Agreement[]};
const names:Record<string,string>={let_only:'Let Only',rent_collection:'Rent Collection',full_management:'Full Management'};
export default function ServiceAgreements({propertyId,landlordId}:{propertyId?:number;landlordId?:number}){
 const api=useApi(),{user,token}=useAuth(),{confirmAction}=useNotifications();const [rows,setRows]=useState<Agreement[]>([]),[context,setContext]=useState<Context|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[setup,setSetup]=useState(''),[monthly,setMonthly]=useState(''),[signatory,setSignatory]=useState(''),[preview,setPreview]=useState<{subject:string;html:string;to:string}|null>(null);
 const load=useCallback(async()=>{try{const data=await api.get(propertyId?`/api/properties/${propertyId}/service-agreements`:`/api/landlords/${landlordId}/service-agreements`);if(propertyId){setContext(data);setRows(data.agreements);if(data.directors.length===1)setSignatory(data.directors[0].name);}else setRows(data);}catch(e){setError(e instanceof Error?e.message:'Could not load service agreements');}},[api,propertyId,landlordId]);
 useEffect(()=>{void load();},[load]);
 const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:'Could not save service agreement');}finally{setBusy(false);}};
 const pdf=async(a:Agreement)=>{try{const response=await fetch(`${import.meta.env.VITE_API_URL||''}/api/service-agreements/${a.id}/pdf`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw Error('Could not download agreement');const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=`${names[a.service_type]} Service Agreement.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}};
 if(user?.role==='viewer'||context?.property.landlord_type==='internal')return null;
 return <Card className="p-6"><h2 className="font-semibold">Service Contracts</h2><p className="text-xs text-[var(--text-muted)] mt-2">A signed service agreement is required before marketing or starting tenant onboarding. Manage each agreement from its property record.</p>
 {error&&<p role="alert" className="text-sm text-red-600 mt-3">{error}</p>}
 <div className="space-y-4 mt-4">{rows.map(a=><div key={a.id} className={`border rounded-xl p-4 ${a.status==='signed'?'border-emerald-500/40 bg-emerald-500/5':'border-[var(--border-subtle)]'}`}>
 <div className="flex justify-between gap-3"><strong>{names[a.service_type]}{a.property_address&&<> · <Link to={`/properties/${a.property_id}`}>{a.property_address}</Link></>}</strong><span className="capitalize">{a.status}</span></div><p className="text-sm mt-2">Set-up: {a.setup_fee}%{a.service_type!=='let_only'&&` · Monthly: ${a.monthly_fee}%`}</p>
 {a.issued_at&&<p className="text-xs mt-2">Issued {new Date(a.issued_at).toLocaleString('en-GB')} · Email: {a.delivery_status||'Not sent'}</p>}
 {a.signed_at&&<div className="text-sm mt-3"><p>Approved by Landlord · {a.signer_name} · {new Date(a.signed_at).toLocaleString('en-GB')}</p><p className="text-xs mt-1">{a.bank_changed?'Alternative bank details approved for this property':'Bank details confirmed'}: {a.bank_details.account_name} · {a.bank_details.sort_code} · ending {a.bank_details.account_number.slice(-4)}</p></div>}
 {a.delivery_error&&<p className="text-sm text-red-600 mt-2">{a.delivery_error}</p>}
 <div className="flex flex-wrap gap-2 mt-3"><Button size="sm" variant="outline" onClick={()=>void pdf(a)}>Download {a.status==='signed'?'Signed ':''}PDF</Button>
 {propertyId&&['draft','issued'].includes(a.status)&&<><Button size="sm" variant="outline" disabled={busy} onClick={()=>void action(async()=>setPreview(await api.post(`/api/service-agreements/${a.id}/preview`,{})))}>Email Preview</Button><Button size="sm" disabled={busy} onClick={()=>void action(()=>api.post(`/api/service-agreements/${a.id}/send`,{}))}>{a.status==='draft'?'Send for Signing':'Resend / Chase'}</Button>{a.status==='issued'&&<a className="text-xs underline self-center" target="_blank" rel="noreferrer" href={a.signing_url}>Signing Link</a>}</>}
 {propertyId&&['admin','manager'].includes(user?.role||'')&&a.status!=='void'&&<Button size="sm" variant="outline" disabled={busy} onClick={async()=>{if(await confirmAction('Void this service agreement? Its signed copy will be retained, and further onboarding will require a replacement.','Void Service Agreement'))void action(()=>api.post(`/api/service-agreements/${a.id}/void`,{}));}}>Void</Button>}</div></div>)}</div>
 {propertyId&&context&&!rows.some(a=>a.status!=='void')&&<div className="mt-4"><p className="font-medium text-sm">Create {names[context.property.service_type]} Agreement</p><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,200px),1fr))] gap-3 mt-3"><Input label="Set-up Fee (% of first rent)" type="number" value={setup} onChange={setSetup}/>{context.property.service_type!=='let_only'&&<Input label="Monthly Fee (%)" type="number" value={monthly} onChange={setMonthly}/>}<Input label="Company Director / Signatory" value={signatory} onChange={setSignatory}/></div><Button className="mt-4" disabled={busy} onClick={()=>void action(()=>api.post(`/api/properties/${propertyId}/service-agreements`,{setup_fee:setup,monthly_fee:monthly,signatory_name:signatory}))}>{busy?'Preparing…':'Create Draft'}</Button></div>}
 {!propertyId&&!rows.length&&<p className="text-sm mt-3">No service agreements issued. Open a linked property to create one.</p>}
 {preview&&<div className="fixed inset-0 z-50 bg-black/50 p-4 grid place-items-center"><div className="bg-white text-black rounded-xl p-5 w-full max-w-3xl"><div className="flex justify-between gap-3"><div><strong>{preview.subject}</strong><p className="text-sm">To: {preview.to}</p></div><Button variant="outline" className="!text-black !border-gray-300" onClick={()=>setPreview(null)}>Close</Button></div><iframe title="Service agreement email preview" sandbox="" srcDoc={preview.html} className="w-full h-[65vh] border-0 mt-4"/></div></div>}
 </Card>;
}
