import {createPortal} from 'react-dom';
import {useState} from 'react';
import {Plus} from 'lucide-react';
import {Button,Select} from './ui';
import {useApi} from '../hooks/useApi';
type Template={id:string;label:string;subject:string;html:string;sms:string};
export default function TenantMessageTemplates({tenantId,onSent}:{tenantId:number;onSent:()=>void}){
 const api=useApi();const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[channel,setChannel]=useState('email'),[chosen,setChosen]=useState('');
 const [data,setData]=useState<{email:string;phone:string;templates:Template[]}>({email:'',phone:'',templates:[]});const template=data.templates.find(t=>t.id===chosen);
 const load=async()=>{setBusy(true);setError('');try{const result=await api.get(`/api/tenants/${tenantId}/message-templates?at=${Date.now()}`);setData(result);setChosen(result.templates[0]?.id||'');setOpen(true);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const send=async()=>{if(!template)return;setBusy(true);setError('');try{if(channel==='email')await api.post('/api/email/send-generic',{entity_type:'tenant',entity_id:tenantId,to_email:data.email,subject:template.subject,body_html:template.html});else await api.post('/api/sms/send',{entity_type:'tenant',entity_id:tenantId,to_phone:data.phone,message_body:template.sms});setOpen(false);onSent();}catch(e){setError(e instanceof Error?e.message:'Sending could not be confirmed. Check communications before retrying.');}finally{setBusy(false);}};
 return <><Button size="sm" variant="outline" disabled={busy} onClick={()=>void load()}><Plus size={14}/> Send Template</Button>{error&&!open&&<p role="alert">{error}</p>}{open&&createPortal(<div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-4"><div role="dialog" aria-modal="true" aria-label="Send template" className="bg-[var(--bg-card)] rounded-2xl p-6 w-full max-w-2xl max-h-[90vh] overflow-auto space-y-4"><h2 className="font-semibold text-lg">Send Template</h2>{data.templates.length?<><Select label="Template" value={chosen} onChange={setChosen} options={data.templates.map(t=>({value:t.id,label:t.label}))}/><Select label="Send Via" value={channel} onChange={setChannel} options={[{value:'email',label:'Email'},{value:'sms',label:'SMS'}]}/><p className="text-sm">To: {channel==='email'?data.email||'No email recorded':data.phone||'No phone recorded'}</p>{template&&(channel==='email'?<iframe title="Email preview" sandbox="" srcDoc={template.html} className="w-full h-96 bg-white rounded-xl"/>:<p className="p-4 rounded-xl bg-[var(--bg-subtle)] whitespace-pre-wrap">{template.sms}</p>)}</>:<p>No overdue rent or tenancy-end reminders apply to this tenant.</p>}{error&&<p role="alert" className="text-red-500">{error}</p>}<div className="flex justify-end gap-3"><Button variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!template||!(channel==='email'?data.email:data.phone)} onClick={()=>void send()}>{busy?'Sending…':'Send'}</Button></div></div></div>,document.body)}</>;
}
