import {createPortal} from 'react-dom';
import {useState} from 'react';
import {Mail,MessageSquare} from 'lucide-react';
import {Button,Input} from './ui';
import {useApi} from '../hooks/useApi';
import {useNotifications} from '../context/NotificationContext';
import {emailTemplateFields,fillTemplate,fieldLabel} from '../utils/emailTemplates';
type Template={id:string;label:string;subject?:string;html?:string;sms?:string};
export default function TenantMessageTemplates({tenantId,onSent}:{tenantId:number;onSent:()=>void}){
 const api=useApi();const {confirmAction}=useNotifications();const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[channel,setChannel]=useState('email'),[chosen,setChosen]=useState(''),[values,setValues]=useState<Record<string,string>>({});
 const [data,setData]=useState<{email:string;phone:string;templates:Template[];smsTemplates:Template[]}>({email:'',phone:'',templates:[],smsTemplates:[]});const list=channel==='email'?data.templates:data.smsTemplates;const template=list.find(t=>t.id===chosen);const fields=emailTemplateFields(template?.html||'');const html=fillTemplate(template?.html||'',values);
 const load=async()=>{setBusy(true);setError('');try{const result=await api.get(`/api/tenants/${tenantId}/message-templates?at=${Date.now()}`);setData(result);setChannel('email');setChosen(result.templates[0]?.id||'');setValues({});setOpen(true);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const send=async()=>{if(!template)return;if(!await confirmAction('Are you sure that you wish to send this communication?'))return;setBusy(true);setError('');try{if(channel==='email')await api.post('/api/email/send-generic',{entity_type:'tenant',entity_id:tenantId,to_email:data.email,subject:template.subject,body_html:html});else await api.post('/api/sms/send',{entity_type:'tenant',entity_id:tenantId,to_phone:data.phone,message_body:template.sms});setOpen(false);onSent();}catch(e){setError(e instanceof Error?e.message:'Sending could not be confirmed. Check communications before retrying.');}finally{setBusy(false);}};
 return <><Button size="sm" variant="outline" className="gap-2 !bg-purple-500/10 !text-[var(--feedback-purple)] !border-purple-500/20" disabled={busy} onClick={()=>void load()}><Mail size={14}/> Send Template</Button>{error&&!open&&<p role="alert">{error}</p>}{open&&createPortal(<div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-4"><div role="dialog" aria-modal="true" aria-label="Send template" className="bg-[var(--bg-card)] text-[var(--text-primary)] rounded-2xl p-6 w-full max-w-5xl max-h-[90vh] overflow-auto space-y-4"><h2 className="font-semibold text-lg">Send Template</h2><div className="flex gap-2">{['sms','email'].map(c=><Button key={c} variant="outline" className={channel===c?'gap-2 !bg-purple-500/15 !text-[var(--feedback-purple)]':'gap-2'} onClick={()=>{setChannel(c);setChosen((c==='email'?data.templates:data.smsTemplates)[0]?.id||'');setValues({});}}>{c==='email'?<Mail size={15}/>:<MessageSquare size={15}/>} {c==='email'?'Email Templates':'SMS Templates'}</Button>)}</div><p className="text-sm">To: {channel==='email'?data.email||'No email recorded':data.phone||'No phone recorded'}</p>
 <div className="grid md:grid-cols-[240px_1fr] gap-4"><div role="listbox" aria-label="Templates" className="space-y-2 max-h-[520px] overflow-y-auto">{list.map(t=><button key={t.id} role="option" aria-selected={chosen===t.id} onClick={()=>{setChosen(t.id);setValues({});}} className={`block w-full rounded-xl p-3 text-left text-sm ${chosen===t.id?'bg-purple-500/15 text-[var(--feedback-purple)]':'bg-[var(--bg-subtle)]'}`}>{t.label}</button>)}</div><div>{template&&(channel==='email'?<><div className="grid sm:grid-cols-2 gap-3 mb-3">{fields.map(f=><Input key={f} label={fieldLabel(f)} value={values[f]||''} onChange={v=>setValues(current=>({...current,[f]:v}))}/>)}</div><iframe title="Email preview" sandbox="" srcDoc={html} className="w-full h-[520px] bg-white rounded-xl"/></>:<p className="p-4 rounded-xl bg-[var(--bg-subtle)] whitespace-pre-wrap">{template.sms}</p>)}</div></div>
 {error&&<p role="alert" className="text-red-500">{error}</p>}<div className="flex justify-end gap-3"><Button variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!template||!(channel==='email'?data.email:data.phone)||(channel==='email'&&fields.some(f=>!values[f]?.trim()))} onClick={()=>void send()}>{busy?'Sending…':'Send'}</Button></div></div></div>,document.body)}</>;
}
