import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import Layout from '../components/Layout';
import { GlassCard, Button, Input, Select, DatePicker } from '../components/ui';
import { useApi } from '../hooks/useApi';
import { useAuth } from '../context/AuthContext';
import { usePortfolio, filterByPortfolio } from '../context/PortfolioContext';
type Inventory = { id: number; property_id: number; property_address: string; inventory_type: string; inspection_date: string; status: string; notes: string; overall_condition: string; room_count: number; photo_count: number };
type Room = { id: number; room_name: string; room_type: string; condition: string; notes: string };
type Photo = { id: number; room_id: number; filename: string; caption: string };
const conditions = ['', 'excellent','good','fair','poor'].map(value => ({value,label:value ? value.charAt(0).toUpperCase()+value.slice(1) : 'Not recorded'}));
function InventoryPhoto({ photo }: { photo: Photo }) {
  const { token } = useAuth(); const [url,setUrl] = useState(''); const [failed,setFailed] = useState(false);
  useEffect(() => { let active=true;let objectUrl='';fetch(`${import.meta.env.VITE_API_URL || ''}/uploads/inventory/${encodeURIComponent(photo.filename)}`, {headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(!r.ok)throw new Error('Photo unavailable');return r.blob();}).then(blob=>{objectUrl=URL.createObjectURL(blob);if(active)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}).catch(()=>setFailed(true));return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[photo.filename,token]);
  return <figure>{url ? <a href={url} target="_blank" rel="noreferrer"><img src={url} alt={photo.caption || 'Inventory photograph'} className="w-full h-44 object-cover rounded-xl" /></a> : <div className="h-44 rounded-xl bg-[var(--bg-hover)] grid place-items-center text-xs">{failed?'Photo unavailable':'Loading photo…'}</div>}<figcaption className="text-xs mt-2">{photo.caption}</figcaption></figure>;
}
export default function Inventories() {
  const { id }=useParams();const navigate=useNavigate();const api=useApi();const { user,token }=useAuth();const { portfolioFilter }=usePortfolio();const editable=user?.role!=='viewer';
  const [items,setItems]=useState<Inventory[]>([]);const [properties,setProperties]=useState<{id:number;address:string;landlord_type:string}[]>([]);const [detail,setDetail]=useState<Inventory|null>(null);const [rooms,setRooms]=useState<Room[]>([]);const [photos,setPhotos]=useState<Photo[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [creating,setCreating]=useState(false);
  const [form,setForm]=useState({property_id:'',inventory_type:'check_in',inspection_date:new Date().toISOString().slice(0,10)});const [newRoom,setNewRoom]=useState('');const [roomType,setRoomType]=useState('other');
  const load=async()=>{try {if(id){const [d,r,p]=await Promise.all([api.get(`/api/inventories/${id}`),api.get(`/api/inventories/${id}/rooms`),api.get(`/api/inventories/${id}/photos`)]);setDetail(d);setRooms(r);setPhotos(p);}else{const [i,p]=await Promise.all([api.get('/api/inventories'),api.get('/api/properties')]);setItems(i);setProperties(p);}}catch(e){setError(e instanceof Error?e.message:'Could not load inventories');}};
  useEffect(()=>{void load();},[id]); // eslint-disable-line react-hooks/exhaustive-deps
  const change=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await load();}catch(e){setError(e instanceof Error?e.message:'Could not save inventory');}finally{setBusy(false);}};
  const upload=async(room:Room,file:File)=>{await change(async()=>{const data=new FormData();data.append('file',file);data.append('caption',room.room_name);const response=await fetch(`${import.meta.env.VITE_API_URL || ''}/api/inventory-photos/${id}/${room.id}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:data});if(!response.ok){const result=await response.json();throw new Error(result.error||'Photo upload failed');}});};
  const scopeProperties=filterByPortfolio(properties,portfolioFilter);const visibleItems=portfolioFilter==='all'?items:items.filter(i=>scopeProperties.some(p=>p.id===i.property_id));
  return <Layout title="Inventory"><div className="p-4 md:p-8 space-y-5 inventory-report"><style>{`@media print { aside,nav,.inventory-controls{display:none!important}body,#root{height:auto!important} .inventory-report{color:#000;background:#fff} .inventory-report img{break-inside:avoid} main,main>div{overflow:visible!important;height:auto!important} }`}</style>
    {error&&<p role="alert" className="text-red-500">{error}</p>}
    {!id?<><div className="flex justify-between gap-3"><h1 className="text-2xl font-semibold">Property Inventories</h1>{editable&&<Button onClick={()=>setCreating(!creating)}>New Inventory</Button>}</div>
      {creating&&<GlassCard className="p-5 space-y-3"><Select label="Property" value={form.property_id} onChange={v=>setForm({...form,property_id:v})} options={[{value:'',label:'Choose property'},...scopeProperties.map(p=>({value:String(p.id),label:p.address}))]} /><Select label="Inspection Type" value={form.inventory_type} onChange={v=>setForm({...form,inventory_type:v})} options={['check_in','check_out','periodic','mid_term'].map(value=>({value,label:value.replaceAll('_',' ')}))}/><DatePicker label="Inspection Date" value={form.inspection_date} onChange={v=>setForm({...form,inspection_date:v})}/><Button disabled={busy||!form.property_id} onClick={()=>change(async()=>{const result=await api.post('/api/inventories',{...form,property_id:Number(form.property_id)});navigate(`/inventories/${result.id}`);})}>Create Inventory</Button></GlassCard>}
      {visibleItems.map(i=><button key={i.id} onClick={()=>navigate(`/inventories/${i.id}`)} className="block w-full text-left"><GlassCard className="p-5"><h2 className="font-semibold">{i.property_address}</h2><p className="text-sm mt-1">{i.inventory_type.replaceAll('_',' ')} · {i.inspection_date.slice(0,10)} · {i.status.replaceAll('_',' ')}</p><p className="text-xs mt-2">{i.room_count} rooms · {i.photo_count} photos</p></GlassCard></button>)}{!visibleItems.length&&<p>No inventories recorded for this portfolio.</p>}</>:
      detail&&<><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">{detail.property_address}</h1><p>{detail.inventory_type.replaceAll('_',' ')} · {detail.inspection_date.slice(0,10)} · {detail.status.replaceAll('_',' ')}</p></div><div className="flex gap-2 inventory-controls"><Button variant="outline" onClick={()=>navigate('/inventories')}>All Inventories</Button><Button variant="outline" onClick={()=>window.print()}>Print / Save PDF</Button></div></div>
      <GlassCard className="p-5 space-y-3">{editable?<><Select label="Overall Condition" value={detail.overall_condition||''} onChange={v=>setDetail({...detail,overall_condition:v})} options={conditions}/><Input label="Inspection Notes" value={detail.notes||''} onChange={v=>setDetail({...detail,notes:v})}/><div className="inventory-controls flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>change(()=>api.put(`/api/inventories/${id}`,{overall_condition:detail.overall_condition,notes:detail.notes,status:detail.status}))}>Save Notes</Button>{detail.status==='in_progress'&&<Button variant="outline" disabled={busy||!rooms.length} onClick={()=>change(()=>api.put(`/api/inventories/${id}/complete`,{}))}>Complete Inspection</Button>}</div></>:<p>{detail.overall_condition} · {detail.notes}</p>}</GlassCard>
      {rooms.map(room=><GlassCard key={room.id} className="p-5 space-y-3"><h2 className="text-lg font-semibold">{room.room_name}</h2>{editable?<><Select label="Condition" value={room.condition||''} onChange={v=>setRooms(current=>current.map(r=>r.id===room.id?{...r,condition:v}:r))} options={conditions}/><Input label="Room Notes" value={room.notes||''} onChange={v=>setRooms(current=>current.map(r=>r.id===room.id?{...r,notes:v}:r))}/><div className="inventory-controls flex flex-wrap items-center gap-3"><Button size="sm" disabled={busy} onClick={()=>change(()=>api.put(`/api/inventory-rooms/${room.id}`,{condition:room.condition||null,notes:room.notes}))}>Save Room</Button><label className="text-sm">Add Photo<input type="file" accept="image/jpeg,image/png" capture="environment" disabled={busy} className="block max-w-full mt-1 text-xs" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(room,file);e.target.value='';}}/></label></div></>:<p>{room.condition} · {room.notes}</p>}<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{photos.filter(p=>p.room_id===room.id).map(p=><InventoryPhoto key={p.id} photo={p}/>)}</div></GlassCard>)}
      {editable&&<GlassCard className="p-5 space-y-3 inventory-controls"><h2 className="font-semibold">Add Room</h2><Input label="Room Name" value={newRoom} onChange={setNewRoom}/><Select label="Room Type" value={roomType} onChange={setRoomType} options={['bedroom','living_room','kitchen','bathroom','hallway','garden','other'].map(value=>({value,label:value.replaceAll('_',' ')}))}/><Button disabled={busy||!newRoom.trim()} onClick={()=>change(async()=>{await api.post(`/api/inventories/${id}/rooms`,{room_name:newRoom,room_type:roomType});setNewRoom('');})}>Add Room</Button></GlassCard>}</>}
  </div></Layout>;
}
