import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import Layout from '../components/Layout';
import {Button,GlassCard,Input,Select} from '../components/ui';
import {useApi} from '../hooks/useApi';
import {useAuth} from '../context/AuthContext';
import {useNotifications} from '../context/NotificationContext';
import {Download,Mail,MessageSquare,Upload,FileText,CheckCircle2,Clock,Users,User} from 'lucide-react';
import {type EmailTemplate,emailTemplateFields,fillTemplate,fieldLabel,resolveKnownEmailImages} from '../utils/emailTemplates';
type Contact={entity_type:string;id:number;name:string;email:string;phone:string;audience:string;email_allowed:boolean;sms_allowed:boolean};
type Campaign={id:string;name:string;channel:string;subject:string;message:string;message_format?:string;status:string;from_email?:string;sender_name?:string;sender_email?:string;created_at?:string;started_at?:string;total_count?:number;delivered_count?:number;failed_count?:number;success_rate?:number|null;counts:{status:string;count:number}[]};
export default function Marketing(){
 const api=useApi();const {token,user}=useAuth();const {confirmAction}=useNotifications();
 const [contacts,setContacts]=useState<Contact[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[audience,setAudience]=useState('All'),[search,setSearch]=useState(''),[selected,setSelected]=useState<string[]>([]),[templates,setTemplates]=useState<EmailTemplate[]>([]);
 const [mode,setMode]=useState('manual'),[templateId,setTemplateId]=useState(''),[rawHtml,setRawHtml]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[fileName,setFileName]=useState('');
 const [fromEmail,setFromEmail]=useState('contact@tenancies.fleminglettings.co.uk');
 const [assets,setAssets]=useState<{name:string;url:string}[]>([]),[attachments,setAttachments]=useState<{id:number;name:string;size:number}[]>([]),[signatures,setSignatures]=useState<{id:string;label:string;html:string}[]>([]),[signatureId,setSignatureId]=useState('02-viewing-confirmation.html'),[reportFilter,setReportFilter]=useState('all');
 const [campaignName,setCampaignName]=useState('');
 const [channel,setChannel]=useState('email'),[subject,setSubject]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [permission,setPermission]=useState<Contact|null>(null),[emailPermission,setEmailPermission]=useState('out'),[smsPermission,setSmsPermission]=useState('out');
 const [preview,setPreview]=useState<(Campaign&{attachments?:{id:number;name:string;size:number}[];recipients:{name:string;destination:string;status:string;error?:string;marketing_allowed?:boolean}[]})|null>(null),[draftId,setDraftId]=useState<string|null>(null);
 const permitted=['admin','manager'].includes(user?.role||'');const html=fillTemplate(rawHtml,values);const escape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const manualHtml=`<div style="font-family:Arial;white-space:pre-wrap;padding:24px">${escape(text)}</div>${signatures.find(s=>s.id===signatureId)?.html||''}`;const message=channel==='email'?(mode==='manual'?manualHtml:html):text;
 const fields=emailTemplateFields(rawHtml).filter(k=>k!=='FIRST_NAME');const missingFields=fields.filter(k=>!values[k]?.trim());
 const imageSources=[...new Set([...rawHtml.matchAll(/<img[^>]*\bsrc=["']([^"']+)["']/gi)].map(m=>m[1]))];
 useEffect(()=>{if(!permitted)return;let active=true;const load=()=>Promise.all([api.get('/api/marketing/contacts'),api.get('/api/marketing/campaigns'),api.get('/api/message-templates'),api.get('/api/marketing/assets'),api.get('/api/marketing/signatures')]).then(([a,b,c,d,e])=>{if(active){setContacts(a);setCampaigns(b);setTemplates(c);setAssets(d);setSignatures(e);}}).catch(e=>{if(active)setError(e.message);});void load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer);};},[api,permitted]);
 const filtered=contacts.filter(c=>(audience==='All'||c.audience===audience)&&`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));const key=(c:Contact)=>`${c.entity_type}:${c.id}`;
 const eligible=(c:Contact)=>channel==='email'?!!c.email&&c.email_allowed:!!c.phone&&c.sms_allowed;
 const reset=()=>{setAttachments([]);setCampaignName('');setText('');setSubject('');setRawHtml('');setValues({});setFileName('');setTemplateId('');setMode('manual');setDraftId(null);setError('');};
 const send=async()=>{setError('');setNotice('');if(!selected.length){setError('Select at least one recipient.');return;}if(channel==='email'&&!subject.trim()){setError('Enter an email subject.');return;}if(!(channel==='email'&&mode!=='manual'?message:text).trim()){setError('Write a message or choose an HTML template.');return;}if(channel==='email'&&mode!=='manual'&&missingFields.length){setError('Complete these template details: '+missingFields.map(fieldLabel).join(', '));return;}
  if(!await confirmAction('Are you sure that you wish to send this communication?'))return;
  setBusy(true);try{let id=draftId;if(!id){const result=await api.post('/api/marketing/campaigns',{name:campaignName.trim()||subject||'SMS Campaign',channel,subject,message,message_format:channel==='email'?'html':'text',from_email:fromEmail,attachment_ids:attachments.map(f=>f.id),recipients:selected});id=result.id;setDraftId(id);}await api.post(`/api/marketing/campaigns/${id}/send`,{});reset();setSelected([]);setNotice('Communication queued. Track delivery in Campaign History.');setCampaigns(await api.get('/api/marketing/campaigns'));}catch(e){setError(e instanceof Error?e.message:'Could not queue the communication. Check Campaign History before retrying.');}finally{setBusy(false);}};
 const download=async(all=false)=>{try{const r=await fetch(`${import.meta.env.VITE_API_URL||''}/api/marketing/export${!all&&audience!=='All'?'?audience='+encodeURIComponent(audience):''}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Export failed');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='Fleming Marketing Contacts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}};
 const savePermission=async()=>{if(!permission)return;setBusy(true);setError('');try{for(const [c,destination,value] of [['email',permission.email,emailPermission],['sms',permission.phone,smsPermission]])if(destination)await api.put('/api/marketing/permission',{channel:c,destination,allowed:value==='in'});setContacts(await api.get('/api/marketing/contacts'));setPermission(null);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const loadHtml=async(file?:File)=>{if(!file)return;if(file.size>200000){setError('Choose an HTML file up to 200 KB.');return;}const source=await file.text();setRawHtml(resolveKnownEmailImages(source,templates));setFileName(file.name);setValues({});setDraftId(null);if(!subject.trim())setSubject(new DOMParser().parseFromString(source,'text/html').title||file.name.replace(/\.html?$/i,''));setError('');};
 const replaceImage=async(source:string,file?:File)=>{if(!file)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const r=await fetch(`${import.meta.env.VITE_API_URL||''}/api/marketing/images`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const data=await r.json();if(!r.ok)throw new Error(data.error);setRawHtml(current=>current.split(source).join(data.url));setDraftId(null);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const uploadAsset=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const r=await fetch(`${import.meta.env.VITE_API_URL||''}/api/marketing/images`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const d=await r.json();if(!r.ok)throw Error(d.error);setAssets(await api.get('/api/marketing/assets'));setNotice('Image saved to the asset library. Choose Insert or replace a template image.');}catch(e){setError(String(e));}finally{setBusy(false);}};
 const uploadAttachments=async(files:FileList|null)=>{if(!files)return;setBusy(true);setError('');let total=attachments.reduce((n,f)=>n+f.size,0),count=attachments.length;try{for(const file of Array.from(files)){if(++count>10||(total+=file.size)>15*1024*1024)throw Error('Choose up to 10 attachments totalling no more than 15 MB');const body=new FormData();body.append('file',file);const r=await fetch(`${import.meta.env.VITE_API_URL||''}/api/marketing/attachments`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const d=await r.json();if(!r.ok)throw Error(d.error);setAttachments(current=>current.some(f=>f.id===d.id)?current:[...current,d]);setDraftId(null);}}catch(e){setError(String(e));}finally{setBusy(false);}};
 const insertAsset=(asset:{url:string;name:string})=>{const tag=`<p><img src="${asset.url}" alt="${escape(asset.name)}" style="max-width:100%;height:auto"/></p>`;setRawHtml(current=>/<\/body>/i.test(current)?current.replace(/<\/body>/i,tag+'</body>'):current+tag);setDraftId(null);};
 return <Layout title="Marketing"><div className="p-4 md:p-8 space-y-6">{!permitted?<p>Marketing access is available to managers and administrators.</p>:<>
 <div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-semibold">Marketing</h1><p className="text-sm text-[var(--text-muted)] mt-2">Choose recipients, preview your message, and send.</p></div><div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="outline" className="gap-2 !text-[var(--feedback-purple)] !bg-purple-500/10 !border-purple-500/20" onClick={()=>download()}><Download size={14}/> Export This Audience</Button><Button size="sm" variant="outline" className="gap-2 !text-[var(--feedback-blue)] !bg-blue-500/10 !border-blue-500/20" onClick={()=>download(true)}><Download size={14}/> Export All Contacts</Button></div></div>
 {error&&<p role="alert" className="text-red-600">{error}</p>}{notice&&<p role="status" className="text-[var(--feedback-emerald)]">{notice}</p>}
 <GlassCard className="p-5 space-y-4"><div className="grid sm:grid-cols-3 gap-4"><Select label="Audience" value={audience} onChange={setAudience} options={['All','Live Landlords','Landlord Enquiries','Live Tenants','Tenant Enquiries','Former Tenants','Closed Landlord Enquiries','Closed Tenant Enquiries'].map(v=>({value:v,label:v}))}/><Input label="Search Contacts" value={search} onChange={setSearch}/><Select label="Send Via" value={channel} onChange={v=>{setChannel(v);setSelected([]);setDraftId(null);}} options={[{value:'email',label:'Email'},{value:'sms',label:'SMS'}]}/></div>
 <div className="flex justify-between gap-4 text-sm"><label className="flex gap-2"><input type="checkbox" checked={filtered.some(eligible)&&filtered.filter(eligible).every(c=>selected.includes(key(c)))} onChange={e=>{setSelected(e.target.checked?[...new Set([...selected,...filtered.filter(eligible).map(key)])]:selected.filter(k=>!filtered.some(c=>key(c)===k)));setDraftId(null);}}/> Select opted-in contacts</label><span className="flex items-center gap-3">{selected.length} selected{!!selected.length&&<Button size="sm" variant="outline" onClick={()=>{setSelected([]);setDraftId(null);}}>Clear All</Button>}</span></div>
 <div className="overflow-auto max-h-96"><table className="w-full text-sm text-left"><thead><tr><th className="p-2">Select</th><th>Name</th><th>Email / Phone</th><th>Audience</th><th>Permission</th></tr></thead><tbody>{filtered.map(c=><tr key={key(c)} className="border-t border-[var(--border-subtle)]"><td className="p-3"><input aria-label={`Select ${c.name}`} type="checkbox" disabled={!eligible(c)} checked={selected.includes(key(c))} onChange={e=>{setSelected(s=>e.target.checked?[...s,key(c)]:s.filter(v=>v!==key(c)));setDraftId(null);}}/></td><td className="p-2">{c.name}</td><td className="p-2"><p>{c.email||'No email'}</p><p className="text-xs text-[var(--text-muted)]">{c.phone||'No phone'}</p></td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[11px] whitespace-nowrap ${c.entity_type.includes('landlord')?'bg-purple-500/10 text-[var(--feedback-purple)]':'bg-blue-500/10 text-[var(--feedback-blue)]'}`}>{c.audience}</span></td><td className="p-2"><button className={`text-xs rounded-full px-2 py-1 ${eligible(c)?'bg-emerald-500/10 text-[var(--feedback-emerald)]':'bg-amber-500/10 text-[var(--feedback-amber)]'}`} onClick={()=>{setPermission(c);setEmailPermission(c.email_allowed?'in':'out');setSmsPermission(c.sms_allowed?'in':'out');setError('');}}>{eligible(c)?'Opted In · Review Permission':'Review Permission'}</button></td></tr>)}</tbody></table></div></GlassCard>
 <GlassCard className="p-5 space-y-4"><Input label="Campaign Name" value={campaignName} onChange={v=>{setCampaignName(v);setDraftId(null);}} placeholder="Tenant update · September 2026"/><h2 className="font-semibold flex gap-2 items-center">{channel==='email'?<Mail size={18}/>:<MessageSquare size={18}/>} Compose {channel==='email'?'Email':'SMS'}</h2>
 {channel==='email'&&<><Input label="Sender Email" type="email" value={fromEmail} onChange={v=>{setFromEmail(v);setDraftId(null);}} placeholder="enquiries@fleminglettings.co.uk"/><div className="flex flex-wrap gap-2">{['contact@tenancies.fleminglettings.co.uk','enquiries@fleminglettings.co.uk','no-reply@fleminglettings.co.uk'].map(email=><Button key={email} size="sm" variant="outline" onClick={()=>{setFromEmail(email);setDraftId(null);}}>{email}</Button>)}</div><div><p className="text-xs font-medium text-[var(--text-secondary)] mb-2">Create Email</p><div role="group" aria-label="Create Email" className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[{value:'manual',label:'Manual Creation',icon:FileText,detail:'Write a message'},{value:'upload',label:'Upload HTML',icon:Upload,detail:'Use your own email design'},{value:'template',label:'Select Template',icon:Mail,detail:'Choose a Fleming template'}].map(({value,label,icon:Icon,detail})=><button type="button" key={value} aria-pressed={mode===value} onClick={()=>{setMode(value);setRawHtml('');setTemplateId('');setValues({});setFileName('');setDraftId(null);}} className={`flex items-center gap-3 rounded-xl border p-4 text-left transition-colors ${mode===value?'border-purple-500/40 bg-purple-500/10':'border-[var(--border-input)] bg-[var(--bg-subtle)] hover:bg-[var(--bg-hover)]'}`}><span className="rounded-lg bg-purple-500/10 p-2 text-[var(--feedback-purple)]"><Icon size={18}/></span><span><strong className="block text-sm">{label}</strong><span className="text-xs text-[var(--text-muted)]">{detail}</span></span></button>)}</div></div><Input label="Subject (required)" value={subject} onChange={v=>{setSubject(v);setDraftId(null);}}/></>}
 {channel==='sms'||mode==='manual'?<label className="block text-sm">Message<textarea aria-label="Message" className="mt-2 w-full rounded-xl border border-[var(--border-input)] bg-[var(--bg-input)] p-3" rows={7} value={text} maxLength={channel==='sms'?1000:200000} onChange={e=>{setText(e.target.value);setDraftId(null);}}/></label>:<>
 {mode==='upload'?<label className="flex items-center justify-center gap-3 p-5 border-2 border-dashed border-[var(--border-input)] rounded-xl cursor-pointer text-sm"><Upload size={20}/>{fileName||'Choose your HTML email'}<input aria-label="Upload HTML" className="sr-only" type="file" accept=".html,.htm,text/html" onChange={e=>void loadHtml(e.target.files?.[0])}/></label>:<Select label="Email Template" value={templateId} onChange={id=>{const t=templates.find(t=>t.id===id);setTemplateId(id);setRawHtml(t?.html||'');setSubject(t?.subject||'');setValues({});setDraftId(null);}} options={[{value:'',label:'Choose a template'},...templates.map(t=>({value:t.id,label:t.label}))]}/>}
 {!!fields.length&&<div className="grid sm:grid-cols-2 gap-3">{fields.map(field=><Input key={field} label={fieldLabel(field)} value={values[field]||''} onChange={v=>{setValues(current=>({...current,[field]:v}));setDraftId(null);}}/>)}</div>}
 {rawHtml&&<><p className="text-xs text-[var(--text-muted)]">First names are filled for each recipient. Complete any template details above before sending.</p><iframe title="Email Preview" sandbox="" srcDoc={fillTemplate(html,{FIRST_NAME:'Recipient'})} className="w-full h-[520px] bg-white rounded-xl border border-[var(--border-input)]"/>
 {!!imageSources.length&&<details className="rounded-xl border border-[var(--border-input)] p-3"><summary className="cursor-pointer text-sm font-medium">Images & Logo</summary><div className="grid sm:grid-cols-2 gap-3 mt-3">{imageSources.map((source,index)=><label key={source} className="flex items-center gap-3 rounded-xl border border-dashed border-purple-500/30 bg-[var(--bg-subtle)] p-4 cursor-pointer hover:bg-purple-500/10"><img src={source} alt="" className="w-14 h-14 rounded-lg object-contain bg-white"/><span className="min-w-0 text-xs truncate">Image {index+1} · {source.split('/').pop()}</span><span className="ml-auto text-xs underline">Replace</span><input aria-label={`Replace image ${index+1}`} type="file" className="sr-only" accept="image/png,image/jpeg,image/webp,image/gif" disabled={busy} onChange={e=>void replaceImage(source,e.target.files?.[0])}/></label>)}</div></details>}</>}
 </>}
 {channel==='email'&&<>{mode==='manual'&&<><Select label="Email Signature" value={signatureId} onChange={v=>{setSignatureId(v);setDraftId(null);}} options={[{value:'',label:'No Signature'},...signatures.map(s=>({value:s.id,label:s.label+' Signature'}))]}/><iframe title="Manual Email Preview" sandbox="" srcDoc={manualHtml} className="w-full h-80 bg-white rounded-xl border"/></>}
 {mode!=='manual'&&<details className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">Image Asset Library</summary><label className="block my-3 text-sm">Upload Image<input type="file" aria-label="Upload asset image" accept="image/png,image/jpeg,image/gif,image/webp" disabled={busy} onChange={e=>void uploadAsset(e.target.files?.[0])}/></label><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 max-h-72 overflow-auto">{assets.map(a=><div key={a.url+a.name} className="rounded-lg border p-2"><img src={a.url} alt={a.name} className="h-16 w-full object-contain bg-white"/><p className="text-xs break-all my-2">{a.name}</p><Button size="sm" variant="outline" onClick={()=>insertAsset(a)}>Insert Image</Button></div>)}</div></details>}
 <div className="rounded-xl border border-dashed p-4"><label className="block text-sm font-medium">Email Attachments<input aria-label="Email Attachments" type="file" multiple accept=".pdf,.docx,.xlsx,.csv,.txt,.jpg,.jpeg,.png" disabled={busy} onChange={e=>{void uploadAttachments(e.target.files);e.target.value='';}}/></label><p className="text-xs text-[var(--text-muted)] mt-2">Up to 8 MB each, 15 MB total. Available for manual, HTML and template emails.</p>{attachments.map(f=><div className="flex items-center justify-between gap-3 mt-2 text-sm" key={f.id}><span>{f.name} · {(f.size/1024).toFixed(0)} KB</span><Button size="sm" variant="outline" onClick={()=>{setAttachments(current=>current.filter(x=>x.id!==f.id));setDraftId(null);}}>Remove</Button></div>)}</div></>}
 <div className="flex justify-end gap-3"><Button variant="ghost" disabled={busy} onClick={reset}>Cancel</Button><Button variant="outline" className="gap-2 !text-[var(--feedback-emerald)] !bg-emerald-500/10 !border-emerald-500/30" disabled={busy} onClick={()=>void send()}><Mail size={15}/>{busy?'Sending…':'Send to Selected Recipients'}</Button></div></GlassCard>
 <GlassCard className="p-5"><div className="flex items-center justify-between gap-3 mb-4"><h2 className="font-semibold">Campaign History</h2><span className="rounded-full bg-purple-500/10 text-[var(--feedback-purple)] px-3 py-1 text-xs">{campaigns.length} campaigns</span></div><div className="space-y-3">{campaigns.length?campaigns.map(c=><button key={c.id} onClick={async()=>{try{setReportFilter('all');setPreview(await api.get(`/api/marketing/campaigns/${c.id}`));}catch(e){setError(String(e));}}} className="block w-full text-left rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-subtle)] p-4 hover:bg-[var(--bg-hover)] transition-colors"><div className="flex flex-wrap justify-between items-start gap-3"><div className="min-w-0"><strong className="block text-sm">{c.name}</strong>{c.subject&&c.subject!==c.name&&<p className="text-xs text-[var(--text-muted)] mt-1 break-words">{c.subject}</p>}<div className="flex flex-wrap items-center gap-x-4 gap-y-2 mt-3 text-xs text-[var(--text-secondary)]"><span className="inline-flex gap-1.5 items-center"><User size={13}/>{c.sender_name||c.sender_email||'Sender not recorded'}</span><span className="inline-flex gap-1.5 items-center"><Clock size={13}/>{c.started_at?'Sent ':'Created '}{c.started_at||c.created_at?new Date(c.started_at||c.created_at!).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'Date not recorded'}</span><span className="inline-flex gap-1.5 items-center"><Users size={13}/>{c.total_count??c.counts.reduce((n,v)=>n+v.count,0)} recipients</span></div></div><div className="flex flex-wrap gap-2"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs ${c.channel==='email'?'bg-blue-500/10 text-[var(--feedback-blue)]':'bg-purple-500/10 text-[var(--feedback-purple)]'}`}>{c.channel==='email'?<Mail size={12}/>:<MessageSquare size={12}/>}{c.channel==='email'?'Email':'SMS'}</span><span className={`rounded-full px-2.5 py-1 text-xs ${c.failed_count?'bg-red-500/10 text-red-600':'bg-emerald-500/10 text-[var(--feedback-emerald)]'}`}>{c.status.replaceAll('_',' ')}</span><span title={`${c.delivered_count||0} confirmed deliveries out of ${c.total_count||0} recipients. Sent messages are awaiting delivery confirmation.`} className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs ${Number(c.success_rate)===100?'bg-emerald-500/15 text-[var(--feedback-emerald)]':'bg-amber-500/15 text-[var(--feedback-amber)]'}`}><CheckCircle2 size={13}/>{c.success_rate==null?'Awaiting send':`${c.success_rate}% delivered`}</span></div></div><p className="text-xs text-[var(--text-muted)] mt-3">{c.counts.map(v=>`${v.count} ${v.status}`).join(' · ')}<span className="float-right inline-flex items-center rounded-full border px-3 py-1 text-[var(--text-primary)]">View Report</span></p></button>):<p className="text-sm text-[var(--text-muted)] py-4">No campaigns yet.</p>}</div></GlassCard></>}
 {permission&&createPortal(<div className="fixed inset-0 z-[90] grid place-items-center bg-black/60 p-4"><div role="dialog" aria-modal="true" aria-label="Review permission" className="bg-[var(--bg-card)] text-[var(--text-primary)] rounded-2xl p-6 max-w-lg w-full space-y-4"><h2 className="font-semibold">{permission.name} · Review Permission</h2><Select label="Email Marketing" value={emailPermission} onChange={setEmailPermission} options={[{value:'in',label:'Opt In'},{value:'out',label:'Opt Out'}]}/><p className="text-xs text-[var(--text-muted)]">{permission.email||'No email recorded — add an email to enable this channel.'}</p><Select label="SMS Communications" value={smsPermission} onChange={setSmsPermission} options={[{value:'in',label:'Opt In'},{value:'out',label:'Opt Out'}]}/><p className="text-xs text-[var(--text-muted)]">{permission.phone||'No phone recorded — add a phone to enable this channel.'}</p>{error&&<p role="alert" className="text-red-600 text-sm">{error}</p>}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setPermission(null)}>Cancel</Button><Button disabled={busy} onClick={()=>void savePermission()}>Save Permissions</Button></div></div></div>,document.body)}
 {preview&&createPortal(<div className="fixed inset-0 z-[90] grid place-items-center bg-black/60 p-4"><div role="dialog" aria-modal="true" aria-label="Campaign Report" className="bg-[var(--bg-card)] text-[var(--text-primary)] rounded-2xl p-6 max-w-2xl w-full max-h-[90vh] overflow-auto space-y-4"><h2 className="font-semibold text-lg">Campaign Report · {preview.name}</h2><p className="text-sm">From: {preview.from_email||'contact@tenancies.fleminglettings.co.uk'}</p><p className="text-sm">{preview.channel} · {preview.recipients.length} unique recipients · {preview.status}</p>{preview.message_format==='html'?<iframe title="Campaign Email Preview" sandbox="" srcDoc={fillTemplate(preview.message,{FIRST_NAME:'Recipient'})} className="w-full h-96 bg-white"/>:<p className="whitespace-pre-wrap">{preview.message}</p>}<Select label="Report Filter" value={reportFilter} onChange={setReportFilter} options={[{value:'all',label:'All Recipients'},{value:'delivered',label:'Delivered'},{value:'bounced',label:'Bounced'},{value:'failed',label:'Rejected / Failed'},{value:'opted_out',label:'Opted Out of Future Mailings'}]}/><div className="overflow-auto max-h-72"><table className="w-full text-left text-sm"><thead><tr><th>Recipient</th><th>Delivery</th><th>Marketing Preference</th></tr></thead><tbody>{preview.recipients.filter(r=>reportFilter==='all'||(reportFilter==='opted_out'?r.marketing_allowed===false:reportFilter==='failed'?['failed','undelivered','complained','rejected'].includes(r.status):reportFilter==='delivered'?['delivered','opened','clicked'].includes(r.status):r.status===reportFilter)).map(r=><tr key={r.destination} className="border-t border-[var(--border-subtle)]"><td className="py-3 pr-3">{r.name}<br/>{r.destination}</td><td className="pr-3">{r.status}{r.error&&<p className="text-xs text-red-600">{r.error}</p>}</td><td>{r.marketing_allowed===false?'Opted out — future mailings blocked':r.marketing_allowed?'Opted in':'No permission recorded'}</td></tr>)}</tbody></table></div>{!!preview.attachments?.length&&<p className="text-sm">Attachments: {preview.attachments.map(f=>f.name).join(', ')}</p>}<div className="flex gap-3">{preview.status==='draft'&&<Button onClick={async()=>{if(!await confirmAction('Are you sure that you wish to send this communication?'))return;try{await api.post(`/api/marketing/campaigns/${preview.id}/send`,{});setPreview(null);setCampaigns(await api.get('/api/marketing/campaigns'));}catch(e){setError(String(e));}}}>Send to Selected Recipients</Button>}<Button variant="ghost" onClick={()=>setPreview(null)}>Close</Button></div></div></div>,document.body)}
 </div></Layout>;
}
