import {useEffect,useState} from 'react';
import Layout from '../components/Layout';
import {Button,GlassCard,Input,Select} from '../components/ui';
import {useApi} from '../hooks/useApi';
import {useAuth} from '../context/AuthContext';
import {useNotifications} from '../context/NotificationContext';
import {Download,Mail,MessageSquare} from 'lucide-react';
type Contact={entity_type:string;id:number;name:string;email:string;phone:string;audience:string;email_allowed:boolean;sms_allowed:boolean};
type Campaign={id:string;name:string;channel:string;subject:string;message:string;message_format?:string;status:string;counts:{status:string;count:number}[]};
export default function Marketing(){
 const api=useApi();const {token,user}=useAuth();const {confirmAction}=useNotifications();
 const [contacts,setContacts]=useState<Contact[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[audience,setAudience]=useState('All'),[search,setSearch]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const [messageFormat,setMessageFormat]=useState('text');
 const [channel,setChannel]=useState('email'),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [permission,setPermission]=useState<Contact|null>(null),[evidence,setEvidence]=useState('');
 const [preview,setPreview]=useState<(Campaign&{recipients:{name:string;destination:string;status:string;error?:string}[]})|null>(null);
 const permitted=['admin','manager'].includes(user?.role||'');
 useEffect(()=>{if(!permitted)return;let active=true;const load=()=>Promise.all([api.get('/api/marketing/contacts'),api.get('/api/marketing/campaigns')]).then(([a,b])=>{if(active){setContacts(a);setCampaigns(b);}}).catch(e=>{if(active)setError(e.message);});void load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer);};},[api,permitted]);
 const filtered=contacts.filter(c=>(audience==='All'||c.audience===audience)&&`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));
 const key=(c:Contact)=>`${c.entity_type}:${c.id}`;
 const eligible=(c:Contact)=>channel==='email'?!!c.email&&c.email_allowed:!!c.phone&&c.sms_allowed;
 const create=async()=>{setBusy(true);setError('');try{const created=await api.post('/api/marketing/campaigns',{name:subject||'SMS Campaign',channel,subject,message,message_format:messageFormat,recipients:selected});setPreview(await api.get(`/api/marketing/campaigns/${created.id}`));setCampaigns(await api.get('/api/marketing/campaigns'));}catch(e){setError(e instanceof Error?e.message:'Campaign could not be saved');}finally{setBusy(false);}};
 const download=async(all=false)=>{try{const r=await fetch(`${import.meta.env.VITE_API_URL||''}/api/marketing/export${!all&&audience!=='All'?'?audience='+encodeURIComponent(audience):''}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Export failed');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='Fleming Marketing Contacts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}};
 const savePermission=async(allowed:boolean)=>{if(!permission)return;setBusy(true);try{await api.put('/api/marketing/permission',{channel,destination:channel==='email'?permission.email:permission.phone,allowed,evidence});setContacts(await api.get('/api/marketing/contacts'));setPermission(null);setEvidence('');}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <Layout title="Marketing"><div className="p-4 md:p-8 space-y-6">{!permitted?<p>Marketing access is available to managers and administrators.</p>:<>
 <div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-semibold">Marketing</h1><p className="text-sm text-[var(--text-muted)] mt-2">Choose your audience, review the message, and track each delivery.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>download()}><Download size={15}/> Export This Audience</Button><Button variant="outline" onClick={()=>download(true)}>Export All Contacts</Button></div></div>
 {error&&<p role="alert" className="text-red-600">{error}</p>}
 <GlassCard className="p-5 space-y-4"><div className="grid sm:grid-cols-3 gap-4"><Select label="Audience" value={audience} onChange={setAudience} options={['All','Live Landlords','Landlord Enquiries','Live Tenants','Tenant Enquiries','Former Tenants','Closed Landlord Enquiries','Closed Tenant Enquiries'].map(v=>({value:v,label:v}))}/><Input label="Search Contacts" value={search} onChange={setSearch}/><Select label="Send Via" value={channel} onChange={v=>{setChannel(v);setSelected([]);}} options={[{value:'email',label:'Email'},{value:'sms',label:'SMS'}]}/></div>
 <div className="flex justify-between gap-4 text-sm"><label className="flex gap-2"><input type="checkbox" checked={filtered.some(eligible)&&filtered.filter(eligible).every(c=>selected.includes(key(c)))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...filtered.filter(eligible).map(key)])]:selected.filter(k=>!filtered.some(c=>key(c)===k)))}/> Select eligible contacts</label><span>{selected.length} selected</span></div>
 <div className="overflow-auto max-h-96"><table className="w-full text-sm text-left"><thead><tr><th className="p-2">Select</th><th>Name</th><th>Email / Phone</th><th>Audience</th><th>Marketing Permission</th></tr></thead><tbody>{filtered.map(c=><tr key={key(c)} className="border-t border-[var(--border-subtle)]"><td className="p-3"><input aria-label={`Select ${c.name}`} type="checkbox" disabled={!eligible(c)} checked={selected.includes(key(c))} onChange={e=>setSelected(s=>e.target.checked?[...s,key(c)]:s.filter(v=>v!==key(c)))}/></td><td className="p-2">{c.name}</td><td className="p-2"><p>{c.email||'No email'}</p><p className="text-xs text-[var(--text-muted)]">{c.phone||'No phone'}</p></td><td className="p-2">{c.audience}</td><td className="p-2"><button className={`underline ${eligible(c)?'text-emerald-700':'text-amber-700'}`} onClick={()=>{setPermission(c);setEvidence('');}}>{eligible(c)?'Allowed':'Record Permission'}</button></td></tr>)}</tbody></table></div>
 <p className="text-xs text-[var(--text-muted)]">Only contacts with recorded permission for this channel can receive a campaign. Duplicate destinations are sent once. Every message includes an opt-out link.</p></GlassCard>
 <GlassCard className="p-5 space-y-4"><h2 className="font-semibold flex gap-2 items-center">{channel==='email'?<Mail size={18}/>:<MessageSquare size={18}/>} Compose {channel==='email'?'Email':'SMS'}</h2>{channel==='email'&&<Input label="Subject" value={subject} onChange={setSubject}/>}
 {channel==='email'&&<div className="space-y-3"><Select label="Email Format" value={messageFormat} onChange={setMessageFormat} options={[{value:'text',label:'Plain Text'},{value:'html',label:'HTML Template'}]}/>{messageFormat==='html'&&<label className="block text-sm">Upload HTML<input aria-label="Upload HTML" type="file" accept=".html,.htm,text/html" className="block mt-2" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>200000){setError('Choose an HTML file up to 200 KB');return;}setMessage(await file.text());}}/></label>}</div>}
 <label className="block text-sm">{messageFormat==='html'&&channel==='email'?'HTML Source':'Message'}<textarea className="mt-2 w-full rounded-xl border border-[var(--border-input)] bg-[var(--bg-input)] p-3" rows={7} value={message} maxLength={channel==='sms'?1000:200000} onChange={e=>setMessage(e.target.value)}/></label>{channel==='email'&&messageFormat==='html'&&message&&<iframe title="HTML Template Preview" sandbox="" srcDoc={message} className="w-full h-96 bg-white rounded-xl"/>}<Button disabled={busy||!message.trim()||!selected.length||(channel==='email'&&!subject.trim())} onClick={create}>Save Draft & Review {selected.length} Recipients</Button></GlassCard>
 <GlassCard className="p-5"><h2 className="font-semibold mb-4">Campaign History</h2>{campaigns.length?campaigns.map(c=><button key={c.id} onClick={async()=>{try{setPreview(await api.get(`/api/marketing/campaigns/${c.id}`));}catch(e){setError(String(e));}}} className="block w-full text-left border-t border-[var(--border-subtle)] py-3"><strong>{c.name}</strong><span className="ml-3 text-sm">{c.channel} · {c.status.replaceAll('_',' ')}</span><p className="text-xs mt-1">{c.counts.map(v=>`${v.count} ${v.status}`).join(' · ')}</p></button>):<p className="text-sm">No campaigns yet.</p>}</GlassCard>
 </>}
 {permission&&<div className="fixed inset-0 z-[90] grid place-items-center bg-black/60 p-4"><div role="dialog" aria-modal="true" aria-label="Marketing permission" className="bg-[var(--bg-card)] rounded-2xl p-6 max-w-lg w-full space-y-4"><h2 className="font-semibold">{permission.name} · {channel==='email'?'Email':'SMS'} Permission</h2><p className="text-sm">Record when and how this person agreed to receive marketing through this channel.</p><textarea aria-label="Permission evidence" rows={4} value={evidence} onChange={e=>setEvidence(e.target.value)} className="w-full rounded-lg border p-3 bg-[var(--bg-input)]"/><div className="flex flex-wrap gap-2"><Button disabled={busy||evidence.trim().length<10} onClick={()=>savePermission(true)}>Record Permission</Button><Button variant="outline" disabled={busy} onClick={()=>savePermission(false)}>Opt Out</Button><Button variant="ghost" onClick={()=>setPermission(null)}>Cancel</Button></div></div></div>}
 {preview&&<div className="fixed inset-0 z-[90] grid place-items-center bg-black/60 p-4"><div role="dialog" aria-modal="true" aria-label="Review campaign" className="bg-[var(--bg-card)] rounded-2xl p-6 max-w-2xl w-full max-h-[90vh] overflow-auto space-y-4"><h2 className="font-semibold text-lg">{preview.subject||preview.name}</h2><p className="text-sm">{preview.channel} · {preview.recipients.length} unique recipients · {preview.status}</p><div className="rounded-lg bg-[var(--bg-subtle)] p-4"><p className="font-semibold mb-2">Fleming Lettings</p><>{preview.message_format==='html'?<iframe title="Campaign Email Preview" sandbox="" srcDoc={preview.message} className="w-full h-96 bg-white"/>:<p className="whitespace-pre-wrap">{preview.message}</p>}</><p className="text-xs underline mt-4">Unsubscribe link included for each recipient</p></div><ul className="text-sm space-y-2 max-h-52 overflow-auto">{preview.recipients.map(r=><li key={r.destination}>{r.name} · {r.destination} · {r.status}{r.error?' — '+r.error:''}</li>)}</ul><div className="flex gap-3">{preview.status==='draft'&&<Button disabled={busy} onClick={async()=>{if(!await confirmAction(`Send this ${preview.channel} campaign to ${preview.recipients.length} recipients?`))return;setBusy(true);try{await api.post(`/api/marketing/campaigns/${preview.id}/send`,{});setPreview(null);setSelected([]);setCampaigns(await api.get('/api/marketing/campaigns'));}catch(e){setError(String(e));}finally{setBusy(false);}}}>Send Campaign</Button>}<Button variant="ghost" onClick={()=>setPreview(null)}>Close</Button></div></div></div>}
 </div></Layout>;
}
