import DepartmentTeams from '../components/DepartmentTeams';
import {useEffect,useState,useCallback} from 'react';
import Layout from '../components/Layout';
import {GlassCard,Button,Input,Select,Avatar,DataTable,type Column} from '../components/ui';
import PermissionRequests from '../components/ui/PermissionRequests';
import TeamActivity from '../components/ui/TeamActivity';
import {useApi} from '../hooks/useApi';
import {useAuth} from '../context/AuthContext';
import {useNotifications} from '../context/NotificationContext';
import {Plus,X,Shield,Users as UsersIcon,Eye,ShieldAlert,Archive,Building2,UserCheck} from 'lucide-react';
type User={id:number;name:string;email:string;role:string;department?:string;phone?:string;office_extension?:string;finance_access?:boolean;is_active:number;password_setup_required?:boolean;created_at:string;last_login?:string};
type Request={id:number;kind:string;email:string;requester_name?:string;approver_id?:number;created_at:string;payload:{name?:string;role?:string;finance_access?:boolean;department?:string}};
const empty={name:'',email:'',role:'staff',department:'',phone:'',office_extension:'',finance_access:false,approver_id:''};
const roleNames:Record<string,string>={admin:'Administrator',manager:'Manager',staff:'Staff',viewer:'Viewer'};
export default function Users(){
 const api=useApi(),{user}=useAuth(),{confirmAction}=useNotifications();
 const admin=user?.role==='admin',allowed=admin||user?.role==='manager';
 const [departments,setDepartments]=useState<{id:number;name:string}[]>([]);
 const [users,setUsers]=useState<User[]>([]),[requests,setRequests]=useState<Request[]>([]),[loading,setLoading]=useState(true),[archived,setArchived]=useState(false),[search,setSearch]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<User|null>(null),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const [people,pending,teams]=await Promise.all([api.get('/api/users'),api.get('/api/account-requests'),api.get('/api/departments')]);setDepartments(teams);setUsers(people);setRequests(pending);}catch(e){setError(e instanceof Error?e.message:'Could not load the team');}finally{setLoading(false);}},[api]);
 useEffect(()=>{if(allowed)void load();},[load,allowed]);
 const action=async(work:()=>Promise<unknown>,success:string)=>{setBusy(true);setError('');try{await work();setMessage(success);await load();return true;}catch(e){setError(e instanceof Error?e.message:'The request failed');return false;}finally{setBusy(false);}};
 const open=(person:User|null)=>{setEditing(person);setForm(person?{...empty,...person,department:person.department||'',phone:person.phone||'',office_extension:person.office_extension||'',finance_access:person.finance_access===true}:empty);setError('');setModal(true);};
 const save=async()=>{if(await action(()=>editing?api.put(`/api/users/${editing.id}`,form):api.post('/api/users',form),editing?'Account updated.':admin?'Invitation emailed. The link expires in 48 hours.':'Account request sent for administrator approval.'))setModal(false);};
 const icons={admin:ShieldAlert,manager:Shield,staff:UsersIcon,viewer:Eye};
 const columns:Column<User>[]=[{key:'name',header:'User',render:u=><div className="flex gap-3 items-center"><Avatar name={u.name} size="sm"/><div><p className="font-medium">{u.name}</p><p className="text-xs text-[var(--text-muted)]">{u.email}</p></div></div>},{key:'role',header:'Role',render:u=>{const Icon=icons[u.role as keyof typeof icons]||UsersIcon;return <span className="inline-flex items-center gap-1.5 rounded-full bg-[var(--bg-subtle)] px-3 py-1 text-xs"><Icon size={14}/>{roleNames[u.role]}</span>;}},{key:'department',header:'Department',render:u=>u.department||'—'},{key:'status',header:'Status',render:u=><span className={u.is_active?'text-emerald-500':'text-[var(--text-muted)]'}>{!u.is_active?'Archived':u.password_setup_required?'Invitation pending':'Active'}</span>},{key:'actions',header:'',render:u=>admin?<div className="flex gap-2"><Button size="sm" variant="ghost" onClick={()=>open(u)}>Edit</Button>{!!u.is_active&&<Button size="sm" variant="ghost" disabled={busy} onClick={async()=>{if(await confirmAction(`Email ${u.name} a ${u.password_setup_required?'new activation':'password reset'} link?`))void action(()=>api.put(`/api/users/${u.id}/reset-password`,{}),'Secure link emailed. It expires in 48 hours.');}}>{u.password_setup_required?'Resend Invitation':'Reset Password'}</Button>}<Button size="sm" variant="ghost" disabled={busy||u.id===user?.id} onClick={async()=>{if(await confirmAction(`${u.is_active?'Deactivate':'Reactivate'} ${u.name}?`))void action(()=>api.put(`/api/users/${u.id}`,{is_active:u.is_active?0:1}),'Account status updated.');}}>{u.is_active?'Deactivate':'Reactivate'}</Button></div>:null}];
 if(!allowed)return <Layout title="Team"><p className="p-8">Team management requires a manager or administrator account.</p></Layout>;
 return <Layout title="Team Management" breadcrumb={[{label:'Team'}]}><div className="p-4 md:p-8 space-y-6">
 {error&&<p role="alert" className="text-red-500">{error}</p>}{message&&<p role="status" className="text-emerald-500">{message}</p>}
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{[{label:'Active',count:users.filter(u=>u.is_active).length,icon:UserCheck,color:'bg-emerald-500/15 text-emerald-600'},{label:'Administrators',count:users.filter(u=>u.is_active&&u.role==='admin').length,icon:ShieldAlert,color:'bg-blue-500/15 text-blue-600'},{label:'Teams / Offices',count:departments.length,icon:Building2,color:'bg-yellow-500/15 text-yellow-600'},{label:'Archived',count:users.filter(u=>!u.is_active).length,icon:Archive,color:'bg-red-500/15 text-red-600'}].map(({label,count,icon:Icon,color})=><GlassCard key={label} className="p-4 flex gap-3 items-center"><span className={`rounded-full p-3 ${color}`}><Icon size={20}/></span><div><p className="text-sm">{label}</p><p className="text-2xl font-semibold">{count}</p></div></GlassCard>)}</div>
 {requests.length>0&&<GlassCard className="p-4 space-y-3"><h2 className="font-semibold">Pending Account Requests</h2>{requests.map(r=><div key={r.id} className="border-t border-[var(--border-color)] pt-3 flex flex-wrap items-center gap-3"><div className="flex-1"><p className="font-medium">{r.kind==='reset'?'Password reset':'New account'} · {r.email}</p><p className="text-xs text-[var(--text-muted)]">{r.kind==='create'?`${r.payload.name} · ${roleNames[r.payload.role||'staff']} · ${r.payload.department||'No department'} · Financials ${r.payload.finance_access?'enabled':'disabled'} · Requested by ${r.requester_name}`:'Requested from the sign-in page'} · {new Date(r.created_at).toLocaleString('en-GB')}{r.approver_id?` · Approver: ${users.find(u=>u.id===r.approver_id)?.name||'Administrator'}`:''}</p></div>{admin&&(!r.approver_id||r.approver_id===user?.id)&&<><Button size="sm" disabled={busy} onClick={()=>void action(()=>api.post(`/api/account-requests/${r.id}/decision`,{decision:'approve'}),'Request approved and account link emailed.')}>Approve & Send Link</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void action(()=>api.post(`/api/account-requests/${r.id}/decision`,{decision:'reject'}),'Request rejected.')}>Reject</Button></>}</div>)}</GlassCard>}
 <DepartmentTeams teams={departments} users={users} onSaved={load}/>
 {admin&&<><PermissionRequests/><TeamActivity users={users}/></>}
 <GlassCard className="p-4 flex flex-wrap gap-3 items-center"><Input value={search} onChange={setSearch} placeholder="Search team"/><Button variant={archived?'ghost':'primary'} size="sm" onClick={()=>setArchived(false)}>Active</Button><Button variant={archived?'primary':'ghost'} size="sm" onClick={()=>setArchived(true)}>Archived</Button><Button size="sm" className="ml-auto" onClick={()=>open(null)}><Plus size={16}/>{admin?'Add User':'Request User'}</Button></GlassCard>
 <GlassCard className="overflow-hidden">{loading?<p className="p-6">Loading…</p>:<DataTable columns={columns} data={users.filter(u=>Boolean(u.is_active)!==archived&&[u.name,u.email,u.role,u.department].some(v=>v?.toLowerCase().includes(search.toLowerCase())))} rowKey={u=>u.id}/>}</GlassCard>
 </div>{modal&&<div className="fixed inset-0 z-50 bg-[var(--overlay-bg)] flex items-center justify-center p-4"><div role="dialog" aria-modal="true" aria-label={editing?'Edit user':'Add user'} className="w-full max-w-lg bg-[var(--bg-card)] p-6 rounded-2xl space-y-4 max-h-[90vh] overflow-auto"><div className="flex justify-between"><h2 className="font-semibold">{editing?'Edit User':admin?'Invite User':'Request User'}</h2><button aria-label="Close" onClick={()=>setModal(false)}><X/></button></div><Input label="Name" value={form.name} onChange={name=>setForm({...form,name})}/><Input label="Email" type="email" value={form.email} onChange={email=>setForm({...form,email})}/><Select label="Role" value={form.role} onChange={role=>setForm({...form,role})} options={[{value:'admin',label:'Administrator — Full system access'},{value:'manager',label:'Manager — Records, Financials and account requests'},{value:'staff',label:'Staff — Edit records and onboard clients'},{value:'viewer',label:'Viewer — Read only'}]}/><Select label="Department / Team" value={form.department} onChange={department=>setForm({...form,department})} options={[{value:'',label:'No Department'},...departments.map(d=>({value:d.name,label:d.name}))]}/><Input label="Mobile Number" type="tel" value={form.phone} onChange={phone=>setForm({...form,phone})}/><Input label="Office Extension" value={form.office_extension} onChange={office_extension=>setForm({...form,office_extension})}/><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={form.finance_access} onChange={e=>setForm({...form,finance_access:e.target.checked})}/>Allow access to Financials Page – required for Accounts Dept</label>{!admin&&<Select label="Administrator to Approve" value={form.approver_id} onChange={approver_id=>setForm({...form,approver_id})} options={[{value:'',label:'Choose administrator'},...users.filter(u=>u.is_active&&u.role==='admin').map(u=>({value:String(u.id),label:u.name}))]}/>}{error&&<p role="alert" className="text-red-500 text-sm">{error}</p>}<p className="text-xs text-[var(--text-muted)]">{editing?'Role changes take effect immediately.':'After administrator approval, an invitation is emailed. The user must set their password within 48 hours before signing in.'}</p><Button disabled={busy} onClick={()=>void save()}>{busy?'Saving…':editing?'Save Changes':admin?'Send Invitation':'Submit Request'}</Button></div></div>}</Layout>;
}
